In [61]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [62]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [63]:
balance  = pd.read_csv('../data/dseb63_credit_card_balance.csv')
balance

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,...,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
0,2582071,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.0,2250.0,...,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0,87788
1,2582071,-82,16809.210,67500,0.0,0.0,0.0,0.0,3375.0,9000.0,...,16809.210,0.0,0,0.0,0.0,18.0,Active,0,0,87788
2,2582071,-84,27577.890,67500,0.0,0.0,0.0,0.0,3375.0,4500.0,...,27577.890,0.0,0,0.0,0.0,16.0,Active,0,0,87788
3,2582071,-7,65159.235,45000,0.0,0.0,0.0,0.0,2250.0,2250.0,...,65609.235,0.0,0,0.0,0.0,63.0,Active,0,0,87788
4,2582071,-59,70475.850,67500,24750.0,24750.0,0.0,0.0,3375.0,4500.0,...,70475.850,4.0,4,0.0,0.0,41.0,Active,0,0,87788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227960,1551072,-1,0.000,202500,NaN,0.0,NaN,NaN,0.0,NaN,...,0.000,NaN,0,NaN,NaN,0.0,Active,0,0,259579
3227961,2339982,-1,0.000,45000,0.0,0.0,0.0,0.0,0.0,NaN,...,0.000,0.0,0,0.0,0.0,0.0,Active,0,0,220697
3227962,2720102,-1,0.000,225000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.000,NaN,0,NaN,NaN,0.0,Active,0,0,93573
3227963,1897864,-2,0.000,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.000,NaN,0,NaN,NaN,0.0,Active,0,0,11072
3227964,2481982,-1,0.000,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.000,NaN,0,NaN,NaN,0.0,Active,0,0,258032

## From https://github.com/minerva-ml/open-solution-home-credit/blob/solution-5/notebooks/eda-credit_card.ipynb

In [64]:
# balance['AMT_DRAWINGS_ATM_CURRENT'][balance['AMT_DRAWINGS_ATM_CURRENT'] < 0] = np.nan
# balance['AMT_DRAWINGS_CURRENT'][balance['AMT_DRAWINGS_CURRENT'] < 0] = np.nan

In [65]:
balance.columns

Index(['SK_ID_PREV', 'MONTHS_BALANCE', 'AMT_BALANCE',
       'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT',
       'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT',
       'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY',
       'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT',
       'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE',
       'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT',
       'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT',
       'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD',
       'SK_DPD_DEF', 'SK_ID_CURR'],
      dtype='object')

In [66]:
balance['NAME_CONTRACT_STATUS'].value_counts()

NAME_CONTRACT_STATUS
Active           3116673
Completed         100031
Signed              9939
Demand               843
Sent proposal        460
Refused               14
Approved               5
Name: count, dtype: int64

In [67]:
balance[balance['NAME_CONTRACT_STATUS'] == 'Completed']

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,...,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
310,1441883,-3,0.0,270000,0.0,0.00,0.0,0.0,0.000,0.0,...,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
311,1441883,-4,0.0,270000,0.0,1448.64,0.0,0.0,1159.155,0.0,...,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
312,1441883,-2,0.0,270000,0.0,0.00,0.0,0.0,0.000,0.0,...,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
316,1441883,-1,0.0,270000,0.0,0.00,0.0,0.0,0.000,0.0,...,0.0,0.0,0,0.0,0.0,3.0,Completed,0,0,85482
426,2016842,-3,0.0,0,0.0,0.00,0.0,0.0,0.000,0.0,...,0.0,0.0,0,0.0,0.0,2.0,Completed,0,0,280613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227131,1797458,-2,0.0,180000,NaN,0.00,NaN,NaN,0.000,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Completed,0,0,19531
3227193,2716904,-1,0.0,45000,NaN,0.00,NaN,NaN,0.000,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Completed,0,0,121014
3227228,2466603,-3,0.0,90000,NaN,0.00,NaN,NaN,0.000,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Completed,0,0,33204
3227542,2378003,-4,0.0,180000,NaN,0.00,NaN,NaN,0.000,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Completed,0,0,286313
3227844,1463847,-1,0.0,225000,NaN,0.00,NaN,NaN,0.000,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Completed,0,0,32545

In [68]:
display_missing_data_info(balance)

                            Missing Values  Percentage (%)
AMT_PAYMENT_CURRENT                 620093       19.210029
AMT_DRAWINGS_ATM_CURRENT            605754       18.765817
AMT_DRAWINGS_OTHER_CURRENT          605754       18.765817
AMT_DRAWINGS_POS_CURRENT            605754       18.765817
CNT_DRAWINGS_ATM_CURRENT            605754       18.765817
CNT_DRAWINGS_OTHER_CURRENT          605754       18.765817
CNT_DRAWINGS_POS_CURRENT            605754       18.765817
AMT_INST_MIN_REGULARITY             264384        8.190423
CNT_INSTALMENT_MATURE_CUM           264384        8.190423

                            Missing Values  Percentage (%)
AMT_PAYMENT_CURRENT                 620093       19.210029
AMT_DRAWINGS_ATM_CURRENT            605754       18.765817
AMT_DRAWINGS_OTHER_CURRENT          605754       18.765817
AMT_DRAWINGS_POS_CURRENT            605754       18.765817
CNT_DRAWINGS_ATM_CURRENT            605754       18.765817
CNT_DRAWINGS_OTHER_CURRENT          605754       18.765817
CNT_DRAWINGS_POS_CURRENT            605754       18.765817
AMT_INST_MIN_REGULARITY             264384        8.190423
CNT_INSTALMENT_MATURE_CUM           264384        8.190423

In [69]:
balance[balance['AMT_DRAWINGS_ATM_CURRENT'].isnull()]

,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,...,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,SK_ID_CURR
313,1441883,-10,0.0,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,85482
314,1441883,-11,0.0,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,85482
315,1441883,-8,0.0,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,85482
317,1441883,-9,0.0,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,85482
318,1441883,-12,0.0,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,85482
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3227959,2181012,-2,0.0,135000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,4322
3227960,1551072,-1,0.0,202500,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,259579
3227962,2720102,-1,0.0,225000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,93573
3227963,1897864,-2,0.0,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,11072
3227964,2481982,-1,0.0,270000,NaN,0.0,NaN,NaN,0.0,NaN,...,0.0,NaN,0,NaN,NaN,0.0,Active,0,0,258032

### Select 
Group by id prev
- Count month
- Count completed
- Count signed
- Cound demand
- Count Sent Proposal
- Count Refused
- Count Approved
- Change in Limit 
- Average Limit
- Var Limit
- Count mo
- Min regular mean
- Change in regular mean

- Utilize rate
- Count utilize < 25%
- Count utilize < 50%
- Count utilize < 75%
- Count utilize < 100%
- Count utilize > 100%
- Count account balance != 0
- max_month/total record

- Count drawning
- Count drawning ATM
- Drawning ATM/Drawning


- Max Drawing (ATM)
- Sum drawing atm
- Sum drawing current

- Mean diff principal vs reciable


### 6 month/ 1 year/ 3 years
- Max Drawing
- Sum Drawing
- Count drawning
- Drawning ATM/Drawning
- Count utilize < 50%
- Count utilize < 100%
- Average Limit

In [70]:
balance["ACTIVE"] = balance["NAME_CONTRACT_STATUS"].apply(lambda x: 1 if x == "Active" else 0)
balance["COMPLETED"] = balance["NAME_CONTRACT_STATUS"].apply(lambda x: 1 if x == "Completed" else 0)
balance["DEMAND"] = balance["NAME_CONTRACT_STATUS"].apply(lambda x: 1 if x == "Demand" else 0)
balance["REFUSED"] = balance["NAME_CONTRACT_STATUS"].apply(lambda x: 1 if x == "Refused" else 0)
balance["SENT_PROPOSAL"] = balance["NAME_CONTRACT_STATUS"].apply(lambda x: 1 if x == "Sent proposal" else 0)
balance["SIGNED"] = balance["NAME_CONTRACT_STATUS"].apply(lambda x: 1 if x == "Signed" else 0)

In [71]:
balance['UTILIZATION'] = balance['AMT_BALANCE'] / (balance['AMT_CREDIT_LIMIT_ACTUAL'] + 1e-6)

# v1.2
mask = (balance['AMT_CREDIT_LIMIT_ACTUAL'] == 0)
balance.loc[mask, 'UTILIZATION'] = np.nan

In [72]:
balance['RATE_OF_PAYBACK'] = balance['AMT_PAYMENT_TOTAL_CURRENT'] / (balance['AMT_INST_MIN_REGULARITY'] + 1e-6) * (balance['AMT_INST_MIN_REGULARITY']!=0)
balance['PERCENTAGE_OF_MINIMUM_PAYMENTS_MISSED'] = balance['AMT_PAYMENT_CURRENT'] / (balance['AMT_INST_MIN_REGULARITY'] + 1e-6) *  (balance['AMT_INST_MIN_REGULARITY']!=0)

# v1.2
mask = (balance['AMT_INST_MIN_REGULARITY'] == 0)
balance.loc[mask, 'PERCENTAGE_OF_MINIMUM_PAYMENTS_MISSED'] = np.nan
balance.loc[mask, 'RATE_OF_PAYBACK'] = np.nan # v1.2.1

balance['Change_in_Credit_Limit'] = balance['AMT_CREDIT_LIMIT_ACTUAL'] - balance['AMT_CREDIT_LIMIT_ACTUAL'].shift(1)
balance['Change_in_spending'] = balance['AMT_BALANCE'] - balance['AMT_BALANCE'].shift(1)

balance['MINIMUM_PAYMENTS_ONLY'] = balance['AMT_PAYMENT_CURRENT'] == balance['AMT_INST_MIN_REGULARITY']
balance['RAPID_ACCOUNT_TURNOVER'] = balance['CNT_DRAWINGS_CURRENT'] > balance['CNT_DRAWINGS_CURRENT'].shift(1)

In [73]:
balance['SUM_ALL_CNT_DRAWINGS'] = balance['CNT_DRAWINGS_ATM_CURRENT'] + balance['CNT_DRAWINGS_CURRENT'] + balance['CNT_DRAWINGS_OTHER_CURRENT'] + balance['CNT_DRAWINGS_POS_CURRENT']
balance['SUM_ALL_AMT_DRAWINGS'] = balance['AMT_DRAWINGS_ATM_CURRENT'] + balance['AMT_DRAWINGS_CURRENT'] + balance['AMT_DRAWINGS_OTHER_CURRENT'] + balance['AMT_DRAWINGS_POS_CURRENT']
balance['RATIO_ALL_AMT_DRAWINGS_TO_ALL_CNT_DRAWINGS'] = balance['SUM_ALL_AMT_DRAWINGS'] / (balance['SUM_ALL_CNT_DRAWINGS'] + 1e-6) * (balance['SUM_ALL_CNT_DRAWINGS'] != 0)

In [74]:
# v1.2
mask = (balance['SUM_ALL_CNT_DRAWINGS'] == 0)
balance.loc[mask, 'RATIO_ALL_AMT_DRAWINGS_TO_ALL_CNT_DRAWINGS'] = np.nan
balance['RATIO_ALL_AMT_DRAWINGS_TO_ALL_CNT_DRAWINGS'] = balance['RATIO_ALL_AMT_DRAWINGS_TO_ALL_CNT_DRAWINGS'].clip(-9, 9)

In [75]:
balance['UTILIZATION'] = balance['UTILIZATION'].clip(-9, 9) # v1.2 99->9
balance['RATE_OF_PAYBACK'] = balance['RATE_OF_PAYBACK'].clip(-9, 9)
balance['PERCENTAGE_OF_MINIMUM_PAYMENTS_MISSED'] = balance['PERCENTAGE_OF_MINIMUM_PAYMENTS_MISSED'].clip(-9, 9)

In [76]:
balance["POSITIVE_CREDIT"] = np.where(balance["AMT_BALANCE"] > 0, 1, 0)

In [77]:
balance["FLAG_6_MONTHS"] = np.where(balance["MONTHS_BALANCE"] >= -6, 1, 0)
balance["FLAG_12_MONTHS"] = np.where(balance["MONTHS_BALANCE"] >= -12, 1, 0)
balance["FLAG_36_MONTHS"] = np.where(balance["MONTHS_BALANCE"] >= -36, 1, 0)

In [78]:
balance["FLAG_UTILIZATION_LESS_25"] = np.where(balance["UTILIZATION"] < 0.25, 1, 0)
balance["FLAG_UTILIZATION_LESS_50"] = np.where(balance["UTILIZATION"] < 0.50, 1, 0)
balance["FLAG_UTILIZATION_LESS_75"] = np.where(balance["UTILIZATION"] < 0.75, 1, 0)
balance["FLAG_UTILIZATION_LESS_100"] = np.where(balance["UTILIZATION"] < 1.00, 1, 0)
balance["FLAG_UTILIZATION_MORE_100"] = np.where(balance["UTILIZATION"] > 1.00, 1, 0)

In [79]:
balance['PRINCIPIAL_RATE'] = balance['AMT_RECEIVABLE_PRINCIPAL'] / (balance['AMT_TOTAL_RECEIVABLE'] + 1e-6)

In [80]:
balance['PRINCIPIAL_RATE'] = balance['PRINCIPIAL_RATE'].clip(0, 99)

In [ ]:

gb_balance = balance.groupby('SK_ID_CURR').agg({
    'MONTHS_BALANCE': ['count'],
    'ACTIVE': 'sum',
    'COMPLETED': 'sum',
    'DEMAND': 'sum',
    'REFUSED': 'sum',
    'SENT_PROPOSAL': 'sum',
    'AMT_BALANCE': 'sum', # Divide later
    'AMT_CREDIT_LIMIT_ACTUAL': ['mean', 'max', 'min', 'nunique', 'std', 'skew'],
    'AMT_INST_MIN_REGULARITY': ['mean', 'max', 'min' , 'nunique', 'skew'],
    'AMT_PAYMENT_TOTAL_CURRENT': ['sum', 'mean', 'max', 'min' , 'std', 'skew'],
    
    'UTILIZATION' : ['sum', 'max', 'min', 'var'], # Divide later
    'FLAG_UTILIZATION_LESS_25' : ['sum', 'mean'],
    'FLAG_UTILIZATION_LESS_50' : ['sum', 'mean'],
    'FLAG_UTILIZATION_LESS_75' : ['sum', 'mean'],
    'FLAG_UTILIZATION_LESS_100' : ['sum', 'mean'],
    'FLAG_UTILIZATION_MORE_100' : ['sum', 'mean'],
    
    'CNT_DRAWINGS_ATM_CURRENT' : ['mean', 'sum', 'std'],
    'CNT_DRAWINGS_CURRENT' : ['mean', 'sum', 'std'],
    
    'AMT_DRAWINGS_ATM_CURRENT' : ['sum', 'mean', 'max', 'min', 'std'],
    'AMT_DRAWINGS_CURRENT' : ['sum', 'mean', 'max', 'min', 'std'],
    'AMT_DRAWINGS_POS_CURRENT' : ['sum', 'mean', 'max', 'min', 'std'],
    'AMT_RECEIVABLE_PRINCIPAL' : 'sum', # Divide later
    'PRINCIPIAL_RATE': 'sum', # Divide later
    'SK_DPD': 'sum',
    'SK_DPD_DEF': 'sum',
    'POSITIVE_CREDIT': 'sum',

    'MINIMUM_PAYMENTS_ONLY' : ['sum', 'mean', 'var'],
    'SUM_ALL_CNT_DRAWINGS' : ['sum', 'mean', 'var'],
    'SUM_ALL_AMT_DRAWINGS' : ['sum', 'mean', 'var', 'max'],
    'RAPID_ACCOUNT_TURNOVER' : ['sum', 'mean', 'var'],
    'RATIO_ALL_AMT_DRAWINGS_TO_ALL_CNT_DRAWINGS' : ['mean', 'var', 'max', 'min'],
    
    'RATE_OF_PAYBACK': ['sum', 'var', 'max', 'min'], # Divide later
    'PERCENTAGE_OF_MINIMUM_PAYMENTS_MISSED': ['sum','var', 'max',], # Divide later
    'Change_in_Credit_Limit': ['sum', 'mean', 'std'],
    'Change_in_spending': ['sum', 'mean', 'std'],
    
}).reset_index()

gb_balance.columns = ['_'.join(col).strip() for col in gb_balance.columns.values]

In [82]:
gb_balance.rename(columns={'SK_ID_CURR_': 'SK_ID_CURR'}, inplace=True)

In [83]:
gb_balance['AMT_BALANCE_sum'] = gb_balance['AMT_BALANCE_sum'] / (gb_balance['POSITIVE_CREDIT_sum']+1)
gb_balance['UTILIZATION_sum'] = gb_balance['UTILIZATION_sum'] / (gb_balance['POSITIVE_CREDIT_sum']+1)
gb_balance['AMT_RECEIVABLE_PRINCIPAL_sum'] = gb_balance['AMT_RECEIVABLE_PRINCIPAL_sum'] / (gb_balance['POSITIVE_CREDIT_sum']+1)
gb_balance['PRINCIPIAL_RATE_sum'] = gb_balance['PRINCIPIAL_RATE_sum'] / (gb_balance['POSITIVE_CREDIT_sum']+1)
gb_balance['RATE_OF_PAYBACK_sum'] = gb_balance['RATE_OF_PAYBACK_sum'] / (gb_balance['POSITIVE_CREDIT_sum']+1)
gb_balance['PERCENTAGE_OF_MINIMUM_PAYMENTS_MISSED_sum'] = gb_balance['PERCENTAGE_OF_MINIMUM_PAYMENTS_MISSED_sum'] / (gb_balance['POSITIVE_CREDIT_sum']+1)

In [84]:
gb_balance['POSITIVE_PERCENT'] = gb_balance['POSITIVE_CREDIT_sum'] / gb_balance['MONTHS_BALANCE_count']

In [85]:
balance_6_months = balance[balance['FLAG_6_MONTHS'] ==1]
balance_12_months = balance[balance['FLAG_12_MONTHS'] ==1]
balance_36_months = balance[balance['FLAG_36_MONTHS'] ==1]

In [86]:
gb_balance_6_months = balance_6_months.groupby('SK_ID_CURR').agg({

    'AMT_BALANCE': 'sum', # Divide later
    'AMT_CREDIT_LIMIT_ACTUAL': ['mean', 'std'],
        'AMT_INST_MIN_REGULARITY': ['mean', 'std'],
    'AMT_PAYMENT_TOTAL_CURRENT': ['sum', 'mean', 'std'],
    
    'UTILIZATION' : 'sum', # Divide later
    'FLAG_UTILIZATION_LESS_50' : ['sum' ,'mean'],
    'FLAG_UTILIZATION_LESS_100' : 'sum',
    
    'CNT_DRAWINGS_ATM_CURRENT' :  'sum',
    'CNT_DRAWINGS_CURRENT' : 'sum',   
    'AMT_DRAWINGS_CURRENT' : ['sum', 'max'],
    'AMT_RECEIVABLE_PRINCIPAL' : 'mean',

    'POSITIVE_CREDIT': 'sum',
}).reset_index()

gb_balance_6_months.columns = ['6_MONTH_'+'_'.join(col).strip() for col in gb_balance_6_months.columns.values]
gb_balance_6_months['6_MONTH_AMT_BALANCE_sum'] = gb_balance_6_months['6_MONTH_AMT_BALANCE_sum'] / (gb_balance_6_months['6_MONTH_POSITIVE_CREDIT_sum']+1e-6)
gb_balance_6_months['6_MONTH_UTILIZATION_sum'] = gb_balance_6_months['6_MONTH_UTILIZATION_sum'] / (gb_balance_6_months['6_MONTH_POSITIVE_CREDIT_sum']+1e-6)
gb_balance_6_months.rename(columns={'6_MONTH_SK_ID_CURR_':'SK_ID_CURR'}, inplace=True)

In [87]:
gb_balance_12_months = balance_12_months.groupby('SK_ID_CURR').agg({
    
        'AMT_BALANCE': 'sum', # Divide later
        'AMT_CREDIT_LIMIT_ACTUAL': ['mean', 'max', 'min', 'std'],
    'AMT_INST_MIN_REGULARITY': ['mean', 'max', 'min', 'std'],
        'AMT_PAYMENT_TOTAL_CURRENT': ['sum', 'mean', 'std'],
        
        'UTILIZATION' : ['sum', 'max', 'min'], # Divide later
        'FLAG_UTILIZATION_LESS_50' : 'sum',
        'FLAG_UTILIZATION_LESS_100' : 'sum',
        
        'CNT_DRAWINGS_ATM_CURRENT' :  'sum',
        'CNT_DRAWINGS_CURRENT' : 'sum',   
        'AMT_DRAWINGS_CURRENT' : ['sum', 'max'],
    
        'POSITIVE_CREDIT': 'sum',
    }).reset_index()

gb_balance_12_months.columns = ['12_MONTH_'+'_'.join(col).strip() for col in gb_balance_12_months.columns.values]
gb_balance_12_months['12_MONTH_AMT_BALANCE_sum'] = gb_balance_12_months['12_MONTH_AMT_BALANCE_sum'] / (gb_balance_12_months['12_MONTH_POSITIVE_CREDIT_sum']+1e-6)
gb_balance_12_months['12_MONTH_UTILIZATION_sum'] = gb_balance_12_months['12_MONTH_UTILIZATION_sum'] / (gb_balance_12_months['12_MONTH_POSITIVE_CREDIT_sum']+1e-6)
gb_balance_12_months.rename(columns={'12_MONTH_SK_ID_CURR_':'SK_ID_CURR'}, inplace=True)

gb_balance_36_months = balance_36_months.groupby('SK_ID_CURR').agg({
        
            'AMT_BALANCE': 'sum', # Divide later
            'AMT_CREDIT_LIMIT_ACTUAL': ['mean', 'std'],
    'AMT_INST_MIN_REGULARITY': ['mean', 'std'],
            'AMT_PAYMENT_TOTAL_CURRENT': ['sum', 'mean',  'std', 'skew'],
            
            'UTILIZATION' : ['sum', 'max', 'min', 'var'], # Divide later
            'FLAG_UTILIZATION_LESS_50' : 'sum',
            'FLAG_UTILIZATION_LESS_100' : 'sum',
            
            'CNT_DRAWINGS_ATM_CURRENT' :  'sum',
            'CNT_DRAWINGS_CURRENT' : 'sum',   
            'AMT_DRAWINGS_CURRENT' : ['sum', 'mean', 'max'],
        
            'POSITIVE_CREDIT': 'sum',
        }).reset_index()

gb_balance_36_months.columns = ['36_MONTH_'+'_'.join(col).strip() for col in gb_balance_36_months.columns.values]
gb_balance_36_months['36_MONTH_AMT_BALANCE_sum'] = gb_balance_36_months['36_MONTH_AMT_BALANCE_sum'] / (gb_balance_36_months['36_MONTH_POSITIVE_CREDIT_sum']+1e-6)
gb_balance_36_months['36_MONTH_UTILIZATION_sum'] = gb_balance_36_months['36_MONTH_UTILIZATION_sum'] / (gb_balance_36_months['36_MONTH_POSITIVE_CREDIT_sum']+1e-6)
gb_balance_36_months.rename(columns={'36_MONTH_SK_ID_CURR_':'SK_ID_CURR'}, inplace=True)

In [88]:
gb_balance = pd.merge(gb_balance, gb_balance_6_months, on='SK_ID_CURR', how='left')
gb_balance = pd.merge(gb_balance, gb_balance_12_months, on='SK_ID_CURR', how='left')
gb_balance = pd.merge(gb_balance, gb_balance_36_months, on='SK_ID_CURR', how='left')

In [89]:
gb_balance.shape

(86905, 157)

In [90]:
gb_balance.to_parquet('../data/dseb63_credit_card_balance_gb_v2.parquet', index=False)