In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [3]:
bureau = pd.read_csv('../data/dseb63_bureau.csv')

In [4]:
appl_train = pd.read_csv('../data/dseb63_application_train.csv')
bureau = pd.merge(bureau, appl_train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')

In [5]:
bureau['CREDIT_TYPE'].value_counts()

CREDIT_TYPE
Consumer credit                                 1069610
Credit card                                      343853
Car loan                                          23757
Mortgage                                          15607
Microloan                                          9005
Loan for business development                      1721
Another type of loan                                854
Unknown type of loan                                472
Loan for working capital replenishment              377
Real estate loan                                     23
Cash loan (non-earmarked)                            23
Loan for the purchase of equipment                   17
Loan for purchase of shares (margin lending)          4
Mobile operator loan                                  1
Interbank credit                                      1
Name: count, dtype: int64

In [6]:
others_loan = ['Another type of loan', 'Unknown type of loan', 'Loan for working capital replenishment', 'Cash loan (non-earmarked)', 'Real estate loan', 'Loan for the purchase of equipment', 'Mobile operator loan', 'Interbank credit', 'Loan for purchase of shares (margin lending)']
mapping_others_loan= {x: 'Others' for x in others_loan}

bureau['CREDIT_TYPE'] = bureau['CREDIT_TYPE'].replace(mapping_others_loan)
bureau

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET
0,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN,254629,0.0
1,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN,254629,0.0
2,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN,254629,0.0
3,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN,254629,0.0
4,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN,254629,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465320,5052629,Closed,currency 1,-532,0,45.0,-227.0,NaN,0,450000.0,0.0,0.0,0.0,Consumer credit,-31,NaN,66820,NaN
1465321,5054382,Closed,currency 1,-381,0,-199.0,-199.0,0.0,0,19800.0,0.0,0.0,0.0,Consumer credit,-199,0.0,166221,NaN
1465322,5043236,Active,currency 1,-1441,0,2197.0,NaN,NaN,0,1800000.0,1076809.5,0.0,0.0,Mortgage,-2,NaN,118290,0.0
1465323,5053303,Closed,currency 1,-375,0,-41.0,-19.0,NaN,0,175054.5,NaN,NaN,0.0,Consumer credit,-4,17140.5,95296,0.0
1465324,5053356,Closed,currency 1,-2724,0,-2511.0,-2511.0,0.0,0,101250.0,0.0,0.0,0.0,Consumer credit,-2510,NaN,139955,0.0

In [7]:
bureau[bureau['TARGET'] == 1].head(20)

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET
155,5714626,Closed,currency 1,-2655,0,-2319.0,-2348.0,0.000,0,20165.400,0.00,0.000,0.0,Consumer credit,-831,NaN,151931,1.0
156,5714627,Closed,currency 1,-2539,0,-1427.0,-651.0,0.000,0,45000.000,0.00,0.000,0.0,Credit card,-651,NaN,151931,1.0
157,5714628,Closed,currency 1,-2343,0,-2008.0,-2219.0,0.000,0,19192.500,0.00,0.000,0.0,Consumer credit,-2219,NaN,151931,1.0
158,5714629,Closed,currency 1,-857,0,-523.0,-582.0,3285.000,0,33853.500,0.00,0.000,0.0,Consumer credit,-582,NaN,151931,1.0
159,5714630,Active,currency 1,-857,0,765.0,NaN,1704.780,0,45000.000,38294.37,6705.630,0.0,Credit card,-675,NaN,151931,1.0
160,5714631,Active,currency 1,-1131,0,-27.0,NaN,NaN,0,270000.000,0.00,0.000,0.0,Credit card,-17,NaN,151931,1.0
161,5714633,Closed,currency 1,-1706,0,-976.0,-1260.0,NaN,0,247500.000,0.00,0.000,0.0,Consumer credit,-538,NaN,151931,1.0
162,5714634,Active,currency 1,-140,0,NaN,NaN,0.000,0,144000.000,143019.00,980.280,0.0,Credit card,-22,NaN,151931,1.0
163,5714632,Closed,currency 1,-2236,0,-1690.0,-1728.0,NaN,0,202500.000,0.00,0.000,0.0,Consumer credit,-538,NaN,151931,1.0
233,5714715,Active,currency 1,-221,0,875.0,NaN,NaN,0,220675.500,NaN,NaN,0.0,Consumer credit,-30,NaN,22407,1.0
234,5714716,Active,currency 1,-221,0,NaN,NaN,NaN,0,90000.000,NaN,NaN,0.0,Credit card,-9,NaN,22407,1.0
235,5714717,Active,currency 1,-728,0,2.0,NaN,3520.800,0,112500.000,5926.50,0.000,0.0,Consumer credit,-27,NaN,22407,1.0
236,5714718,Closed,currency 1,-637,0,-120.0,-120.0,1856.340,0,56532.645,0.00,0.000,0.0,Consumer credit,-120,NaN,22407,1.0
237,5714719,Active,currency 1,-430,0,300.0,NaN,0.000,0,130500.000,78700.50,0.000,0.0,Consumer credit,-34,NaN,22407,1.0
238,5714720,Active,currency 1,-120,0,976.0,NaN,0.000,0,90000.000,67877.19,22122.810,0.0,Credit card,-12,NaN,22407,1.0
239,5714721,Active,currency 1,-120,0,611.0,NaN,0.000,0,180946.845,163820.88,0.000,0.0,Consumer credit,-29,NaN,22407,1.0
337,5714833,Closed,currency 1,-2738,0,-2038.0,-2029.0,140631.840,0,239355.000,0.00,0.000,0.0,Consumer credit,-2029,NaN,80220,1.0
338,5714836,Active,currency 1,-441,0,1386.0,NaN,NaN,0,1115271.000,0.00,NaN,0.0,Consumer credit,-21,NaN,80220,1.0
339,5714837,Closed,currency 1,-1231,0,596.0,-440.0,0.000,0,900000.000,0.00,0.000,0.0,Consumer credit,-395,NaN,80220,1.0
340,5714838,Active,currency 1,-598,0,NaN,NaN,15459.345,0,46089.000,44383.50,1705.095,0.0,Credit card,-22,NaN,80220,1.0

In [8]:
bureau['CREDIT_TYPE'].value_counts()

CREDIT_TYPE
Consumer credit                  1069610
Credit card                       343853
Car loan                           23757
Mortgage                           15607
Microloan                           9005
Others                              1772
Loan for business development       1721
Name: count, dtype: int64

In [9]:
bureau[bureau['CREDIT_ACTIVE'] == 'Bad debt']

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET
6684,5723864,Bad debt,currency 1,-986,0,NaN,NaN,184500.000,0,184500.00,0.000,0.000,0.00,Credit card,-22,NaN,8544,1.0
29866,5801236,Bad debt,currency 1,-2627,0,-1529.0,-1502.0,127866.915,0,225000.00,115349.715,-25349.715,0.00,Credit card,-1502,NaN,106615,NaN
67049,5246470,Bad debt,currency 1,-2386,26,-2296.0,NaN,53532.000,1,58059.00,NaN,NaN,53532.00,Consumer credit,-2296,NaN,219076,NaN
113214,5600466,Bad debt,currency 1,-1046,366,52.0,NaN,NaN,0,135000.00,176233.500,NaN,176233.50,Credit card,-63,NaN,301057,0.0
358515,5173404,Bad debt,currency 1,-2740,1761,-2558.0,NaN,2137.500,0,14296.50,7717.500,0.000,7717.50,Consumer credit,-888,NaN,90732,0.0
464110,5997537,Bad debt,currency 1,-1502,366,-1292.0,NaN,NaN,0,57960.00,0.000,NaN,0.00,Consumer credit,-1292,NaN,128551,0.0
473135,6039562,Bad debt,currency 1,-1683,366,-862.0,NaN,NaN,0,528165.00,NaN,NaN,503392.50,Consumer credit,-1217,NaN,69469,0.0
545313,5499851,Bad debt,currency 1,-1218,366,-852.0,NaN,NaN,0,121275.00,0.000,NaN,0.00,Consumer credit,-1035,NaN,68550,0.0
608323,6439586,Bad debt,currency 1,-2830,0,-2434.0,-1781.0,21741.615,0,58567.68,0.000,0.000,0.00,Consumer credit,-1781,NaN,158804,0.0
608558,6446445,Bad debt,currency 1,-2493,366,-898.0,NaN,NaN,0,162000.00,NaN,NaN,17541.00,Credit card,-1449,NaN,69053,0.0
613922,6441729,Bad debt,currency 1,-2899,0,-1773.0,-1434.0,242637.480,0,365670.72,0.000,0.000,0.00,Consumer credit,-1434,NaN,244804,0.0
697567,5673951,Bad debt,currency 1,-2000,366,-1101.0,NaN,NaN,0,225000.00,NaN,NaN,201366.00,Consumer credit,-1289,NaN,170194,0.0
796723,5309530,Bad debt,currency 1,-2112,0,-1900.0,-1550.0,40871.880,0,22510.89,0.000,0.000,0.00,Consumer credit,-1550,NaN,290806,0.0
825449,5445963,Bad debt,currency 1,-2547,0,-2150.0,-765.0,26410.905,0,41310.00,0.000,0.000,0.00,Consumer credit,-765,NaN,242509,0.0
1206097,5300044,Bad debt,currency 1,-2834,0,-1724.0,-642.0,197937.225,0,135000.00,182632.635,-47632.635,0.00,Credit card,-642,NaN,291484,1.0
1257976,5345303,Bad debt,currency 1,-2728,0,-2514.0,-499.0,10530.000,0,57550.50,0.000,0.000,0.00,Consumer credit,-499,12105.0,231292,NaN
1261464,5326184,Bad debt,currency 1,-2241,1135,-1876.0,NaN,39991.500,0,450000.00,NaN,NaN,42.30,Consumer credit,-737,NaN,167957,NaN
1298637,6166110,Bad debt,currency 1,-2531,1468,-2224.0,NaN,7060.500,0,43627.50,NaN,NaN,2353.77,Consumer credit,-754,NaN,178200,0.0
1316794,5418168,Bad debt,currency 1,-2525,0,-2129.0,-1483.0,61297.650,0,56164.50,0.000,0.000,0.00,Consumer credit,-1483,NaN,259737,0.0
1445396,5550517,Bad debt,currency 1,-2383,0,-1667.0,-1631.0,49828.725,0,97020.00,0.000,0.000,0.00,Consumer credit,-1631,NaN,76539,0.0

In [10]:
not_end =  bureau[~(bureau['DAYS_ENDDATE_FACT']<0)]
not_end

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET
1,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.00,NaN,0.0,Credit card,-20,NaN,254629,0.0
2,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN,254629,0.0
3,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN,254629,0.0
4,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN,254629,0.0
5,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.0,71017.38,108982.62,0.0,Credit card,-31,NaN,254629,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465310,5072148,Active,currency 1,-509,0,584.0,NaN,NaN,0,391500.0,386644.50,0.00,0.0,Credit card,-5,NaN,259236,NaN
1465312,5099978,Active,currency 1,-27,0,399.0,NaN,NaN,0,105543.0,128862.00,NaN,0.0,Consumer credit,-18,NaN,210744,0.0
1465314,5094072,Active,currency 1,-1119,0,-30.0,NaN,NaN,0,270000.0,131085.00,0.00,0.0,Credit card,-15,NaN,82504,0.0
1465316,5044500,Active,currency 1,-420,0,676.0,NaN,NaN,0,135000.0,100008.00,0.00,0.0,Consumer credit,-48,5265.0,82535,NaN
1465322,5043236,Active,currency 1,-1441,0,2197.0,NaN,NaN,0,1800000.0,1076809.50,0.00,0.0,Mortgage,-2,NaN,118290,0.0

In [11]:
bureau['CREDIT_ACTIVE'].value_counts()

CREDIT_ACTIVE
Closed      917733
Active      541919
Sold          5653
Bad debt        20
Name: count, dtype: int64

In [12]:
bureau[bureau['SK_ID_BUREAU'] == 5041336]

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET
566728,5041336,Active,currency 1,-1579,0,-1274.0,NaN,30519.855,0,142317.0,0.0,0.0,0.0,Consumer credit,-111,NaN,158270,1.0

ADD Feature

## General
- Count record
- SUM overdue
- Count currency
- Sum credit
- Sum debt
- Sum overdue
- Count credit_type
- sum everything :))
- Credit sum on Car loan
- Credit sum on Consumer credit
- Credit sum on Credit Card
- Credit sum on Mortgage
- Credit sum on Other

In [13]:
bureau['UNPAID_CREDIT'] = np.where(bureau['DAYS_ENDDATE_FACT'].isnull(), 0, 1)

In [14]:
gb_bureau_general = bureau.groupby('SK_ID_CURR').agg({'SK_ID_BUREAU': 'count', 'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum', 'AMT_CREDIT_SUM_LIMIT':'mean', 'AMT_ANNUITY': 'sum', 'CREDIT_CURRENCY': 'nunique', 'CREDIT_TYPE': 'nunique', 'CREDIT_ACTIVE': 'nunique' }).reset_index()
gb_bureau_general.rename(columns={'SK_ID_BUREAU': 'COUNT_BUREAU'})

sum_on_car_loan = bureau[bureau['CREDIT_TYPE'] == 'Car loan'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
sum_on_car_loan.rename(columns={'AMT_CREDIT_SUM':'SUM_CREDIT_CAR_LOAN', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_CAR_LOAN', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_CAR_LOAN' }, inplace=True)

sum_on_credit_card = bureau[bureau['CREDIT_TYPE'] == 'Credit card'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
sum_on_credit_card.rename(columns={'AMT_CREDIT_SUM':'SUM_CREDIT_CARD', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_CARD', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_CARD' }, inplace=True)

sum_on_mortgage = bureau[bureau['CREDIT_TYPE'] == 'Mortgage'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
sum_on_mortgage.rename(columns={'AMT_CREDIT_SUM':'SUM_MORTGAGE', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_MORTGAGE', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_MORTGAGE' }, inplace=True)

sum_on_consumer_credit = bureau[bureau['CREDIT_TYPE'] == 'Consumer credit'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
sum_on_consumer_credit.rename(columns={'AMT_CREDIT_SUM':'SUM_CONSUMER_CREDIT', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_CONSUMER_CREDIT', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_CONSUMER_CREDIT' }, inplace=True)

sum_on_microloan = bureau[bureau['CREDIT_TYPE'] == 'Microloan'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
sum_on_microloan.rename(columns={'AMT_CREDIT_SUM':'SUM_MICROLOAN', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_MICROLOAN', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_MICROLOAN' }, inplace=True)

sum_on_loan_for_business_development = bureau[bureau['CREDIT_TYPE'] == 'Loan for business development'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
sum_on_loan_for_business_development.rename(columns={'AMT_CREDIT_SUM':'SUM_BUSINESS_DEVELOPMENT', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_BUSINESS_DEVELOPMENT' }, inplace=True)

sum_on_other = bureau[bureau['CREDIT_TYPE']== 'Others'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum'})
sum_on_other.rename(columns={'AMT_CREDIT_SUM':'SUM_OTHER'}, inplace=True)

In [15]:
sum_on_car_loan

,SK_ID_CURR,SUM_CREDIT_CAR_LOAN,SUM_DEBT_CAR_LOAN,SUM_OVERDUE_CAR_LOAN
0,8,2351439.0,0.00,0.0
1,18,2608200.0,1685826.00,0.0
2,47,3972388.5,0.00,0.0
3,54,4252050.0,0.00,0.0
4,69,1675080.0,0.00,0.0
...,...,...,...,...
19570,307347,1620000.0,0.00,0.0
19571,307365,2700000.0,2644735.32,0.0
19572,307393,1395000.0,0.00,0.0
19573,307414,1777500.0,0.00,0.0
19574,307488,4164840.0,0.00,0.0

In [16]:
gb_bureau_general.head()

,SK_ID_CURR,SK_ID_BUREAU,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,AMT_CREDIT_SUM_LIMIT,AMT_ANNUITY,CREDIT_CURRENCY,CREDIT_TYPE,CREDIT_ACTIVE
0,0,1,85513.50,77566.5,0.0,NaN,0.0,1,1,1
1,1,1,28350.00,0.0,0.0,0.0,0.0,1,1,1
2,2,6,254341.08,96417.0,0.0,0.0,0.0,1,1,2
3,3,7,483952.50,198769.5,0.0,0.0,0.0,1,2,2
4,4,6,2822544.00,1254505.5,0.0,0.0,0.0,1,2,2

In [17]:
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_car_loan, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_credit_card, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_mortgage, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_consumer_credit, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_microloan, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_loan_for_business_development, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_other, on='SK_ID_CURR', how='left')
gb_bureau_general.head()

,SK_ID_CURR,SK_ID_BUREAU,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,AMT_CREDIT_SUM_LIMIT,AMT_ANNUITY,CREDIT_CURRENCY,CREDIT_TYPE,CREDIT_ACTIVE,...,SUM_OVERDUE_MORTGAGE,SUM_CONSUMER_CREDIT,SUM_DEBT_CONSUMER_CREDIT,SUM_OVERDUE_CONSUMER_CREDIT,SUM_MICROLOAN,SUM_DEBT_MICROLOAN,SUM_OVERDUE_MICROLOAN,SUM_BUSINESS_DEVELOPMENT,SUM_OVERDUE_BUSINESS_DEVELOPMENT,SUM_OTHER
0,0,1,85513.50,77566.5,0.0,NaN,0.0,1,1,1,...,NaN,85513.50,77566.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,28350.00,0.0,0.0,0.0,0.0,1,1,1,...,NaN,28350.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6,254341.08,96417.0,0.0,0.0,0.0,1,1,2,...,NaN,254341.08,96417.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,7,483952.50,198769.5,0.0,0.0,0.0,1,2,2,...,NaN,335452.50,41071.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6,2822544.00,1254505.5,0.0,0.0,0.0,1,2,2,...,NaN,2552544.00,993028.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
gb_bureau_general.to_csv('../temp/dseb63_bureau_general_v1.csv', index=False)

In [19]:
bureau[bureau['DAYS_CREDIT_ENDDATE'].isnull()]

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET,UNPAID_CREDIT
3,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN,254629,0.0,0
21,5714486,Active,currency 1,-381,0,NaN,NaN,NaN,0,450000.0,520920.0,NaN,0.0,Consumer credit,-4,NaN,60900,0.0,0
24,5714489,Active,currency 1,-392,0,NaN,NaN,0.000,0,252000.0,23679.0,228320.100,0.0,Credit card,-22,NaN,60900,0.0,0
39,5714503,Closed,currency 1,-559,0,NaN,-355.0,0.000,0,110250.0,0.0,0.000,0.0,Credit card,-351,NaN,290333,0.0,1
51,5714518,Active,currency 1,-1483,0,NaN,NaN,NaN,0,200250.0,0.0,NaN,0.0,Credit card,-848,NaN,122422,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465247,5582268,Active,currency 1,-967,0,NaN,NaN,0.000,0,0.0,0.0,0.000,0.0,Credit card,-24,NaN,187253,0.0,0
1465258,5582308,Closed,currency 1,-575,0,NaN,-364.0,NaN,0,225000.0,NaN,NaN,0.0,Consumer credit,-364,NaN,3941,0.0,1
1465271,5088379,Active,currency 1,-602,0,NaN,NaN,0.000,0,45000.0,39424.5,5574.825,0.0,Credit card,-22,4500.0,291862,0.0,0
1465282,5095737,Active,currency 1,-175,0,NaN,NaN,0.000,0,49500.0,42003.0,7494.255,0.0,Credit card,-18,NaN,80556,0.0,0
1465296,5097063,Active,currency 1,-1096,0,NaN,NaN,11713.995,0,135000.0,102433.5,32566.500,0.0,Credit card,-7,NaN,125123,0.0,0

In [20]:
bureau_limit_duration = bureau[~bureau['DAYS_CREDIT_ENDDATE'].isnull()]
bureau_limit_duration

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET,UNPAID_CREDIT
0,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.00,NaN,0.0,Consumer credit,-131,NaN,254629,0.0,1
1,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.00,NaN,0.0,Credit card,-20,NaN,254629,0.0,0
2,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN,254629,0.0,0
4,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN,254629,0.0,0
5,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.0,71017.38,108982.62,0.0,Credit card,-31,NaN,254629,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465320,5052629,Closed,currency 1,-532,0,45.0,-227.0,NaN,0,450000.0,0.00,0.00,0.0,Consumer credit,-31,NaN,66820,NaN,1
1465321,5054382,Closed,currency 1,-381,0,-199.0,-199.0,0.0,0,19800.0,0.00,0.00,0.0,Consumer credit,-199,0.0,166221,NaN,1
1465322,5043236,Active,currency 1,-1441,0,2197.0,NaN,NaN,0,1800000.0,1076809.50,0.00,0.0,Mortgage,-2,NaN,118290,0.0,0
1465323,5053303,Closed,currency 1,-375,0,-41.0,-19.0,NaN,0,175054.5,NaN,NaN,0.0,Consumer credit,-4,17140.5,95296,0.0,1
1465324,5053356,Closed,currency 1,-2724,0,-2511.0,-2511.0,0.0,0,101250.0,0.00,0.00,0.0,Consumer credit,-2510,NaN,139955,0.0,1

In [21]:
bureau_limit_duration[bureau_limit_duration['DAYS_CREDIT_ENDDATE'] > 20000]

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET,UNPAID_CREDIT
5,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.0,71017.38,108982.62,0.0,Credit card,-31,NaN,254629,0.0,0
168,5714639,Closed,currency 1,-2030,0,31111.0,-1750.0,NaN,0,85050.0,0.00,0.00,0.0,Credit card,-555,NaN,80260,NaN,1
213,5714690,Active,currency 1,-137,0,27460.0,NaN,0.0,0,22500.0,18765.63,76.59,0.0,Credit card,-31,NaN,80377,0.0,0
283,5714776,Active,currency 1,-1144,0,31081.0,NaN,NaN,0,225000.0,0.00,0.00,0.0,Credit card,-41,NaN,154187,0.0,0
461,5714983,Active,currency 1,-64,0,27460.0,NaN,0.0,0,22500.0,0.00,22500.00,0.0,Credit card,-17,NaN,219903,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465190,5582125,Active,currency 1,-339,0,27415.0,NaN,0.0,0,90000.0,89350.92,649.08,0.0,Credit card,-21,NaN,101518,0.0,0
1465218,5582222,Active,currency 1,-114,0,27415.0,NaN,NaN,0,90000.0,53644.50,NaN,0.0,Credit card,-21,NaN,259058,0.0,0
1465260,5582349,Active,currency 1,-573,0,27415.0,NaN,0.0,1,270000.0,243131.67,26868.33,0.0,Credit card,-21,NaN,104519,0.0,0
1465273,5095065,Closed,currency 1,-2779,0,31104.0,-1426.0,NaN,0,170010.0,0.00,NaN,0.0,Credit card,-1426,0.0,91029,NaN,1
1465275,5088978,Closed,currency 1,-2591,0,30951.0,-2167.0,NaN,0,0.0,0.00,0.00,0.0,Credit card,-481,0.0,83829,0.0,1

Drop all the Duration < 0

In [22]:
bureau['DAYS_CREDIT_ENDDATE'] = bureau['DAYS_CREDIT_ENDDATE'].fillna(365243)
bureau['DURATION'] = bureau['DAYS_CREDIT_ENDDATE'] - bureau['DAYS_CREDIT']

In [23]:
(bureau['DURATION']<0).sum()

153

In [24]:
bureau = bureau[bureau['DURATION'] >= 0]

In [25]:
bureau_active = bureau[bureau['CREDIT_ACTIVE'] == 'Active']
bureau_active

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET,UNPAID_CREDIT,DURATION
1,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.00,NaN,0.0,Credit card,-20,NaN,254629,0.0,0,1283.0
2,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN,254629,0.0,0,731.0
3,5714465,Active,currency 1,-203,0,365243.0,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN,254629,0.0,0,365446.0
4,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN,254629,0.0,0,1826.0
5,5714467,Active,currency 1,-273,0,27460.0,NaN,0.0,0,180000.0,71017.38,108982.62,0.0,Credit card,-31,NaN,254629,0.0,0,27733.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465310,5072148,Active,currency 1,-509,0,584.0,NaN,NaN,0,391500.0,386644.50,0.00,0.0,Credit card,-5,NaN,259236,NaN,0,1093.0
1465312,5099978,Active,currency 1,-27,0,399.0,NaN,NaN,0,105543.0,128862.00,NaN,0.0,Consumer credit,-18,NaN,210744,0.0,0,426.0
1465314,5094072,Active,currency 1,-1119,0,-30.0,NaN,NaN,0,270000.0,131085.00,0.00,0.0,Credit card,-15,NaN,82504,0.0,0,1089.0
1465316,5044500,Active,currency 1,-420,0,676.0,NaN,NaN,0,135000.0,100008.00,0.00,0.0,Consumer credit,-48,5265.0,82535,NaN,0,1096.0
1465322,5043236,Active,currency 1,-1441,0,2197.0,NaN,NaN,0,1800000.0,1076809.50,0.00,0.0,Mortgage,-2,NaN,118290,0.0,0,3638.0

### Feature for Active
- Count active
- Count active in 30 days
- Count active in 90 days
- Count active in 180 days
- Count active in 365 days
- Count Avaliable in next 30 days
- Count Avaliable in next 180 days
- Count active credit-type
- Count life-time duration

- Total debt in 30 days
- Total credit in 30 days
- Total debt in 180 days
- Total credit in 180 days
- Total debt in 365 days
- Total credit in 365 days

- Total credit life-time

- Average duration (not life-time)
- Sum annuity

In [26]:
def bureau_active_close_feat(bureau_active, status = 'ACTIVE'):    
    bureau_active["LAST_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -30, 1, 0)
    bureau_active["LAST_60_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -60, 1, 0)
    bureau_active["LAST_90_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -90, 1, 0)
    bureau_active["LAST_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -180, 1, 0)
    bureau_active["LAST_365_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -365, 1, 0)
    bureau_active["LAST_730_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -730, 1, 0)
    
    bureau_active["NEXT_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 30, 1, 0)
    bureau_active["NEXT_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 60, 1, 0)
    bureau_active["LIFE_TIME_CREDIT"] = np.where(bureau_active['DAYS_CREDIT_ENDDATE'] >= 16000, 1, 0)

    gb_bureau_active_count = bureau_active.groupby('SK_ID_CURR').agg({ 'SK_ID_BUREAU':'count', 'LAST_30_DAYS': 'sum', 'LAST_60_DAYS': 'sum', 'LAST_90_DAYS': 'sum', 'LAST_180_DAYS': 'sum', 'LAST_365_DAYS': 'sum', 'LAST_730_DAYS':'sum', 'NEXT_30_DAYS': 'sum', 'NEXT_180_DAYS': 'sum', 'LIFE_TIME_CREDIT': 'sum', 'CREDIT_TYPE':'nunique', 'AMT_CREDIT_SUM':'sum', 'AMT_CREDIT_SUM_LIMIT':'sum', 'AMT_ANNUITY':'sum'}).reset_index()
    gb_bureau_active_count.rename(columns={ 'SK_ID_BUREAU':status, 'LAST_30_DAYS':f'{status}_LAST_30_DAYS', 'LAST_60_DAYS':f'{status}_LAST_60_DAYS', 'LAST_90_DAYS':f'{status}_LAST_90_DAYS', 'LAST_180_DAYS':f'{status}_LAST_180_DAYS', 'LAST_365_DAYS':f'{status}_LAST_365_DAYS', 'LAST_730_DAYS':f'{status}_LAST_730_DAYS', 'NEXT_30_DAYS':f'{status}_NEXT_30_DAYS', 'NEXT_180_DAYS':f'{status}_NEXT_180_DAYS', 'LIFE_TIME_CREDIT':f'{status}_LIFE_TIME_CREDIT', 'CREDIT_TYPE':f'{status}_CREDIT_TYPE', 'AMT_CREDIT_SUM': f'{status}_AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_LIMIT':f'{status}_AMT_CREDIT_SUM_LIMIT', 'AMT_ANNUITY':f'{status}_AMT_ANNUITY'}, inplace=True)

    df_30_days = bureau_active[bureau_active['LAST_30_DAYS'] == 1].copy()
    gb_bureau_active_30_days = df_30_days.groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
    gb_bureau_active_30_days.rename(columns={'AMT_CREDIT_SUM':f'{status}_SUM_CREDIT_30_DAYS', 'AMT_CREDIT_SUM_DEBT':f'{status}_SUM_DEBT_30_DAYS', 'AMT_CREDIT_SUM_OVERDUE':f'{status}_SUM_OVERDUE_30_DAYS'}, inplace=True)

    df_180_days = bureau_active[bureau_active['LAST_180_DAYS'] == 1].copy()
    gb_bureau_active_180_days = df_180_days.groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
    gb_bureau_active_180_days.rename(columns={'AMT_CREDIT_SUM':f'{status}_SUM_CREDIT_180_DAYS', 'AMT_CREDIT_SUM_DEBT':f'{status}_SUM_DEBT_180_DAYS', 'AMT_CREDIT_SUM_OVERDUE':f'{status}_SUM_OVERDUE_180_DAYS'}, inplace=True)

    df_life_time_credit = bureau_active[bureau_active['LIFE_TIME_CREDIT'] == 1].copy()
    gb_bureau_active_life_time_credit = df_life_time_credit.groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
    gb_bureau_active_life_time_credit.rename(columns={'AMT_CREDIT_SUM':f'{status}_SUM_CREDIT_LIFE_TIME', 'AMT_CREDIT_SUM_DEBT':f'{status}_SUM_DEBT_LIFE_TIME', 'AMT_CREDIT_SUM_OVERDUE':f'{status}_SUM_OVERDUE_LIFE_TIME'}, inplace=True)

    df_not_life_time_credit = bureau_active[bureau_active['LIFE_TIME_CREDIT'] == 0].copy()
    gb_bureau_active_not_life_time_credit = df_not_life_time_credit.groupby('SK_ID_CURR').agg({'DURATION':'mean'}).reset_index()
    gb_bureau_active_not_life_time_credit.rename(columns={'DURATION':f'{status}_MEAN_DURATION_NOT_LIFE_TIME'}, inplace=True)

    if status == 'ACTIVE':
       
        gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_30_days, on='SK_ID_CURR', how='left')
    gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_180_days, on='SK_ID_CURR', how='left')
    gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_life_time_credit, on='SK_ID_CURR', how='left')
    gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_not_life_time_credit, on='SK_ID_CURR', how='left')
    
    if status == 'CLOSE':
        gb_bureau_active_count.drop(columns=[f'{status}_NEXT_30_DAYS', f'{status}_NEXT_180_DAYS'], inplace=True)
        
        # Add latency here
        
        df_not_life_time_credit['LATENCY_30_DAYS'] = df_not_life_time_credit['LATENCY']*df_not_life_time_credit["LAST_30_DAYS"]
        df_not_life_time_credit['LATENCY_180_DAYS'] = df_not_life_time_credit['LATENCY']*df_not_life_time_credit["LAST_180_DAYS"]
        df_not_life_time_credit['LATENCY_365_DAYS'] = df_not_life_time_credit['LATENCY']*df_not_life_time_credit["LAST_365_DAYS"]
        
        gb_bureau_active_latency = df_not_life_time_credit.groupby('SK_ID_CURR').agg({'LATENCY_30_DAYS':'sum', 'LATENCY_180_DAYS':'sum', 'LATENCY_365_DAYS':'sum', 'LATENCY':'mean'}).reset_index()
        gb_bureau_active_latency.rename(columns={'LATENCY_30_DAYS':'CLOSE_LATENCY_30_DAYS', 'LATENCY_180_DAYS':'CLOSE_LATENCY_180_DAYS', 'LATENCY_365_DAYS':'CLOSE_LATENCY_365_DAYS', 'LATENCY':'CLOSE_MEAN_LATENCY'}, inplace=True)
        gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_latency, on='SK_ID_CURR', how='left')
        
        gb_bureau_active_count['CLOSE_LATENCY_30_DAYS'] = gb_bureau_active_count['CLOSE_LATENCY_30_DAYS']/gb_bureau_active_count['CLOSE_LAST_30_DAYS']
        gb_bureau_active_count['CLOSE_LATENCY_180_DAYS'] = gb_bureau_active_count['CLOSE_LATENCY_180_DAYS']/gb_bureau_active_count['CLOSE_LAST_180_DAYS']
        gb_bureau_active_count['CLOSE_LATENCY_365_DAYS'] = gb_bureau_active_count['CLOSE_LATENCY_365_DAYS']/gb_bureau_active_count['CLOSE_LAST_365_DAYS']
    
    return gb_bureau_active_count

In [27]:
gb_bureau_active_count = bureau_active_close_feat(bureau_active, 'ACTIVE')

C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -30, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_60_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -60, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_90_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -90, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -180, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_365_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -365, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_730_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -730, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["NEXT_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 30, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["NEXT_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 60, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LIFE_TIME_CREDIT"] = np.where(bureau_active['DAYS_CREDIT_ENDDATE'] >= 16000, 1, 0)

In [28]:
gb_bureau_active_count

,SK_ID_CURR,ACTIVE,ACTIVE_LAST_30_DAYS,ACTIVE_LAST_60_DAYS,ACTIVE_LAST_90_DAYS,ACTIVE_LAST_180_DAYS,ACTIVE_LAST_365_DAYS,ACTIVE_LAST_730_DAYS,ACTIVE_NEXT_30_DAYS,ACTIVE_NEXT_180_DAYS,...,ACTIVE_SUM_CREDIT_30_DAYS,ACTIVE_SUM_DEBT_30_DAYS,ACTIVE_SUM_OVERDUE_30_DAYS,ACTIVE_SUM_CREDIT_180_DAYS,ACTIVE_SUM_DEBT_180_DAYS,ACTIVE_SUM_OVERDUE_180_DAYS,ACTIVE_SUM_CREDIT_LIFE_TIME,ACTIVE_SUM_DEBT_LIFE_TIME,ACTIVE_SUM_OVERDUE_LIFE_TIME,ACTIVE_MEAN_DURATION_NOT_LIFE_TIME
0,0,1,0,0,1,1,1,1,1,1,...,NaN,NaN,NaN,85513.50,77566.5,0.0,NaN,NaN,NaN,300.000000
1,1,1,0,0,0,0,0,0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,304.000000
2,2,2,1,2,2,2,2,2,2,2,...,37417.5,38083.5,0.0,101272.50,96417.0,0.0,NaN,NaN,NaN,304.000000
3,3,3,0,0,0,1,2,3,3,3,...,NaN,NaN,NaN,44460.00,35527.5,0.0,NaN,NaN,NaN,636.666667
4,4,3,0,0,0,0,1,2,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1339.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217140,307501,1,0,0,0,0,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4383.000000
217141,307504,1,0,0,0,0,0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1462.000000
217142,307505,2,0,0,0,1,1,1,2,2,...,NaN,NaN,NaN,3078000.00,0.0,0.0,NaN,NaN,NaN,6393.000000
217143,307508,4,0,0,0,1,3,4,4,4,...,NaN,NaN,NaN,104547.33,89635.5,0.0,13500.0,11691.0,0.0,776.000000
217144,307509,1,0,0,0,0,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1318.000000

In [29]:
bureau_closed = bureau[bureau['CREDIT_ACTIVE'] == 'Closed']
bureau_closed

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET,UNPAID_CREDIT,DURATION
0,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN,254629,0.0,1,344.0
7,5714458,Closed,currency 1,-1872,0,-776.0,-1203.0,NaN,0,494550.00,0.0,0.0,0.0,Consumer credit,-696,NaN,254629,0.0,1,1096.0
8,5714459,Closed,currency 1,-1734,0,-638.0,-1336.0,NaN,0,1084032.00,0.0,NaN,0.0,Car loan,-1336,NaN,254629,0.0,1,1096.0
9,5714460,Closed,currency 1,-1333,0,-1089.0,-987.0,NaN,0,102150.00,NaN,NaN,0.0,Consumer credit,-984,NaN,254629,0.0,1,244.0
10,5714461,Closed,currency 1,-1011,0,-830.0,-770.0,NaN,0,500463.00,NaN,NaN,0.0,Consumer credit,-767,NaN,254629,0.0,1,181.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465319,5052615,Closed,currency 1,-697,0,-577.0,-577.0,0.0,0,27169.92,0.0,0.0,0.0,Consumer credit,-572,0.0,302670,0.0,1,120.0
1465320,5052629,Closed,currency 1,-532,0,45.0,-227.0,NaN,0,450000.00,0.0,0.0,0.0,Consumer credit,-31,NaN,66820,NaN,1,577.0
1465321,5054382,Closed,currency 1,-381,0,-199.0,-199.0,0.0,0,19800.00,0.0,0.0,0.0,Consumer credit,-199,0.0,166221,NaN,1,182.0
1465323,5053303,Closed,currency 1,-375,0,-41.0,-19.0,NaN,0,175054.50,NaN,NaN,0.0,Consumer credit,-4,17140.5,95296,0.0,1,334.0
1465324,5053356,Closed,currency 1,-2724,0,-2511.0,-2511.0,0.0,0,101250.00,0.0,0.0,0.0,Consumer credit,-2510,NaN,139955,0.0,1,213.0

In [30]:
bureau

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET,UNPAID_CREDIT,DURATION
0,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN,254629,0.0,1,344.0
1,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN,254629,0.0,0,1283.0
2,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN,254629,0.0,0,731.0
3,5714465,Active,currency 1,-203,0,365243.0,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN,254629,0.0,0,365446.0
4,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN,254629,0.0,0,1826.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465320,5052629,Closed,currency 1,-532,0,45.0,-227.0,NaN,0,450000.0,0.0,0.0,0.0,Consumer credit,-31,NaN,66820,NaN,1,577.0
1465321,5054382,Closed,currency 1,-381,0,-199.0,-199.0,0.0,0,19800.0,0.0,0.0,0.0,Consumer credit,-199,0.0,166221,NaN,1,182.0
1465322,5043236,Active,currency 1,-1441,0,2197.0,NaN,NaN,0,1800000.0,1076809.5,0.0,0.0,Mortgage,-2,NaN,118290,0.0,0,3638.0
1465323,5053303,Closed,currency 1,-375,0,-41.0,-19.0,NaN,0,175054.5,NaN,NaN,0.0,Consumer credit,-4,17140.5,95296,0.0,1,334.0
1465324,5053356,Closed,currency 1,-2724,0,-2511.0,-2511.0,0.0,0,101250.0,0.0,0.0,0.0,Consumer credit,-2510,NaN,139955,0.0,1,213.0

In [31]:
bureau_closed = bureau_closed[bureau_closed['DAYS_ENDDATE_FACT'] >= -16000]

In [32]:
bureau_closed['DAYS_ENDDATE_FACT'].value_counts()

DAYS_ENDDATE_FACT
-329.0     695
-273.0     692
-924.0     679
-925.0     678
-917.0     674
          ...
-2912.0      1
-2916.0      1
-2861.0      1
-2901.0      1
-2915.0      1
Name: count, Length: 2907, dtype: int64

In [33]:
bureau_closed[bureau_closed['DAYS_ENDDATE_FACT'] == -42023]

Empty DataFrame
Columns: [SK_ID_BUREAU, CREDIT_ACTIVE, CREDIT_CURRENCY, DAYS_CREDIT, CREDIT_DAY_OVERDUE, DAYS_CREDIT_ENDDATE, DAYS_ENDDATE_FACT, AMT_CREDIT_MAX_OVERDUE, CNT_CREDIT_PROLONG, AMT_CREDIT_SUM, AMT_CREDIT_SUM_DEBT, AMT_CREDIT_SUM_LIMIT, AMT_CREDIT_SUM_OVERDUE, CREDIT_TYPE, DAYS_CREDIT_UPDATE, AMT_ANNUITY, SK_ID_CURR, TARGET, UNPAID_CREDIT, DURATION]
Index: []

In [34]:
bureau_closed['LATENCY'] =  bureau_closed['DAYS_CREDIT_ENDDATE'] - bureau_closed['DAYS_ENDDATE_FACT']
bureau_closed

C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\873638872.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_closed['LATENCY'] =  bureau_closed['DAYS_CREDIT_ENDDATE'] - bureau_closed['DAYS_ENDDATE_FACT']

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,...,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET,UNPAID_CREDIT,DURATION,LATENCY
0,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,...,NaN,0.0,Consumer credit,-131,NaN,254629,0.0,1,344.0,0.0
7,5714458,Closed,currency 1,-1872,0,-776.0,-1203.0,NaN,0,494550.00,...,0.0,0.0,Consumer credit,-696,NaN,254629,0.0,1,1096.0,427.0
8,5714459,Closed,currency 1,-1734,0,-638.0,-1336.0,NaN,0,1084032.00,...,NaN,0.0,Car loan,-1336,NaN,254629,0.0,1,1096.0,698.0
9,5714460,Closed,currency 1,-1333,0,-1089.0,-987.0,NaN,0,102150.00,...,NaN,0.0,Consumer credit,-984,NaN,254629,0.0,1,244.0,-102.0
10,5714461,Closed,currency 1,-1011,0,-830.0,-770.0,NaN,0,500463.00,...,NaN,0.0,Consumer credit,-767,NaN,254629,0.0,1,181.0,-60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465319,5052615,Closed,currency 1,-697,0,-577.0,-577.0,0.0,0,27169.92,...,0.0,0.0,Consumer credit,-572,0.0,302670,0.0,1,120.0,0.0
1465320,5052629,Closed,currency 1,-532,0,45.0,-227.0,NaN,0,450000.00,...,0.0,0.0,Consumer credit,-31,NaN,66820,NaN,1,577.0,272.0
1465321,5054382,Closed,currency 1,-381,0,-199.0,-199.0,0.0,0,19800.00,...,0.0,0.0,Consumer credit,-199,0.0,166221,NaN,1,182.0,0.0
1465323,5053303,Closed,currency 1,-375,0,-41.0,-19.0,NaN,0,175054.50,...,NaN,0.0,Consumer credit,-4,17140.5,95296,0.0,1,334.0,-22.0
1465324,5053356,Closed,currency 1,-2724,0,-2511.0,-2511.0,0.0,0,101250.00,...,0.0,0.0,Consumer credit,-2510,NaN,139955,0.0,1,213.0,0.0

In [35]:
(bureau_closed['LATENCY'] > 3200).sum()

43040

In [36]:
(bureau_closed['LATENCY'] < 0).sum()

205200

### Feature for close Bureau

- Count close bureau
- Sum overdue
- Count late
- Count early
- AVG duration
- AVG early
- AVG late
- 30 Day
- 90 Day
- 180 Day
- 365 Day
- 730 Day
- Sum annuity

In [37]:
gb_bureau_close_count = bureau_active_close_feat(bureau_closed, 'CLOSE')
gb_bureau_close_count

C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -30, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_60_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -60, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_90_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -90, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -180, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_365_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -365, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_730_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -730, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["NEXT_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 30, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["NEXT_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 60, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\336341716.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LIFE_TIME_CREDIT"] = np.where(bureau_active['DAYS_CREDIT_ENDDATE'] >= 16000, 1, 0)

,SK_ID_CURR,CLOSE,CLOSE_LAST_30_DAYS,CLOSE_LAST_60_DAYS,CLOSE_LAST_90_DAYS,CLOSE_LAST_180_DAYS,CLOSE_LAST_365_DAYS,CLOSE_LAST_730_DAYS,CLOSE_LIFE_TIME_CREDIT,CLOSE_CREDIT_TYPE,...,CLOSE_SUM_DEBT_180_DAYS,CLOSE_SUM_OVERDUE_180_DAYS,CLOSE_SUM_CREDIT_LIFE_TIME,CLOSE_SUM_DEBT_LIFE_TIME,CLOSE_SUM_OVERDUE_LIFE_TIME,CLOSE_MEAN_DURATION_NOT_LIFE_TIME,CLOSE_LATENCY_30_DAYS,CLOSE_LATENCY_180_DAYS,CLOSE_LATENCY_365_DAYS,CLOSE_MEAN_LATENCY
0,2,4,0,0,0,0,1,2,0,1,...,NaN,NaN,NaN,NaN,NaN,205.250000,NaN,NaN,0.0,21.000000
1,3,4,0,0,0,0,0,2,0,1,...,NaN,NaN,NaN,NaN,NaN,349.750000,NaN,NaN,NaN,32.500000
2,4,3,0,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,1156.000000,NaN,NaN,NaN,924.000000
3,5,6,0,0,0,0,1,3,0,1,...,NaN,NaN,NaN,NaN,NaN,1530.500000,NaN,NaN,0.0,1031.333333
4,6,2,0,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,995.500000,NaN,NaN,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230137,307501,4,0,0,0,0,1,1,1,2,...,NaN,NaN,450000.0,0.0,0.0,232.666667,NaN,NaN,0.0,9.666667
230138,307504,3,0,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,302.000000,NaN,NaN,NaN,-1.333333
230139,307506,4,0,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,275.000000,NaN,NaN,NaN,-20.250000
230140,307508,3,0,0,0,0,0,1,0,2,...,NaN,NaN,NaN,NaN,NaN,2090.000000,NaN,NaN,NaN,1064.666667
230141,307509,1,0,0,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,549.000000,NaN,NaN,NaN,6.000000

In [38]:
bureau_closed.dropna(subset=['DAYS_ENDDATE_FACT'], inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\1030630136.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_closed.dropna(subset=['DAYS_ENDDATE_FACT'], inplace=True)

In [39]:
bureau_sold = bureau[bureau['CREDIT_ACTIVE'] == 'Sold']
bureau_sold

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR,TARGET,UNPAID_CREDIT,DURATION
630,5715165,Sold,currency 1,-1319,0,-1134.0,-75.0,133308.81,0,202500.00,0.0,0.0,0.0,Consumer credit,-71,NaN,167888,1.0,1,185.0
868,5715420,Sold,currency 1,-1337,0,-239.0,NaN,NaN,0,477000.00,0.0,NaN,0.0,Consumer credit,-280,NaN,123735,0.0,0,1098.0
1255,5715804,Sold,currency 1,-151,0,764.0,NaN,NaN,0,435973.50,NaN,NaN,0.0,Consumer credit,-24,NaN,281813,0.0,0,915.0
1568,5716119,Sold,currency 1,-2241,0,-1692.0,NaN,NaN,0,142402.50,NaN,NaN,0.0,Credit card,-1967,NaN,144585,0.0,0,549.0
1779,5716347,Sold,currency 1,-2047,0,-1499.0,NaN,NaN,0,153405.00,NaN,NaN,0.0,Credit card,-1957,NaN,266967,0.0,0,548.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463773,6839900,Sold,currency 1,-245,0,851.0,NaN,NaN,0,90000.00,NaN,NaN,0.0,Consumer credit,-25,8611.11,229280,1.0,0,1096.0
1463813,6839973,Sold,currency 1,-2586,0,-1855.0,NaN,82404.00,0,315000.00,NaN,NaN,0.0,Consumer credit,-1929,0.00,220770,0.0,0,731.0
1463868,6840152,Sold,currency 1,-2044,0,-1497.0,NaN,NaN,0,148455.00,NaN,NaN,0.0,Credit card,-2044,8244.00,290452,NaN,0,547.0
1464720,6842758,Sold,currency 1,-2232,0,-1501.0,NaN,NaN,0,156973.50,NaN,NaN,0.0,Credit card,-2200,0.00,65279,0.0,0,731.0
1464808,6842885,Sold,currency 1,-709,0,1117.0,-339.0,0.00,0,461729.07,0.0,0.0,0.0,Consumer credit,-319,NaN,195427,0.0,1,1826.0

### Feature Sold
- Total sold
- Sold finished
- Sold last 90
- Sold last 365
- Sold credit sum

### Feature Bad-Debt
- Total Bad debt
- Bad debt last 365
- Bad debt finished
- Sum credit debt
- Sum bad debt overdue
- Avg duration

In [40]:
bureau_sold = bureau[bureau['CREDIT_ACTIVE'] == 'Sold']

In [41]:
bureau_bad_debt = bureau[bureau['CREDIT_ACTIVE'] == 'Bad debt']

In [42]:
bureau_sold['SOLD_LAST_90_DAYS'] = np.where(bureau_sold['DAYS_CREDIT'].values >= -90, 1, 0)
bureau_sold['SOLD_LAST_365_DAYS'] = np.where(bureau_sold['DAYS_CREDIT'].values >= -365, 1, 0)
bureau_sold['SOLD_LAST_730_DAYS'] = np.where(bureau_sold['DAYS_CREDIT'].values >= -730, 1, 0)

bureau_sold['SOLD_FINISHED'] = np.where(bureau_sold['DAYS_ENDDATE_FACT'].isnull(), 0, 1)
bureau_sold['SOLD_DURATION'] = (bureau_sold['DAYS_ENDDATE_FACT'] - bureau_sold['DAYS_CREDIT']) * bureau_sold['SOLD_FINISHED']

C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\3443005176.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_sold['SOLD_LAST_90_DAYS'] = np.where(bureau_sold['DAYS_CREDIT'].values >= -90, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\3443005176.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_sold['SOLD_LAST_365_DAYS'] = np.where(bureau_sold['DAYS_CREDIT'].values >= -365, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\3443005176.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_sold['SOLD_LAST_730_DAYS'] = np.where(bureau_sold['DAYS_CREDIT'].values >= -730, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\3443005176.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_sold['SOLD_FINISHED'] = np.where(bureau_sold['DAYS_ENDDATE_FACT'].isnull(), 0, 1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\3443005176.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_sold['SOLD_DURATION'] = (bureau_sold['DAYS_ENDDATE_FACT'] - bureau_sold['DAYS_CREDIT']) * bureau_sold['SOLD_FINISHED']

In [43]:
gb_bureau_sold = bureau_sold.groupby('SK_ID_CURR').agg({'SK_ID_BUREAU':'sum', 'SOLD_LAST_90_DAYS': 'sum', 'SOLD_LAST_365_DAYS': 'sum', 'SOLD_LAST_730_DAYS': 'sum', 'SOLD_FINISHED': 'sum', 'SOLD_DURATION':'sum', 'AMT_CREDIT_SUM':'sum' }).reset_index()
gb_bureau_sold.rename(columns={'AMT_CREDIT_SUM':'SOLD_SUM_CREDIT', 'SK_ID_BUREAU':'COUNT_SOLD'}, inplace=True)
gb_bureau_sold['SOLD_DURATION'] = gb_bureau_sold['SOLD_DURATION']/(gb_bureau_sold['SOLD_FINISHED'] + 1e-5)

In [44]:
gb_bureau_sold

,SK_ID_CURR,COUNT_SOLD,SOLD_LAST_90_DAYS,SOLD_LAST_365_DAYS,SOLD_LAST_730_DAYS,SOLD_FINISHED,SOLD_DURATION,SOLD_SUM_CREDIT
0,8,5345624,0,0,0,0,0.0,2351439.0
1,13,10092581,0,0,0,0,0.0,79942.5
2,41,5057224,0,0,0,0,0.0,246951.0
3,46,6496620,0,0,0,0,0.0,255280.5
4,149,6841592,0,0,1,0,0.0,225000.0
...,...,...,...,...,...,...,...,...
5221,307085,5579446,0,0,0,0,0.0,675000.0
5222,307133,6068982,0,1,1,0,0.0,490050.0
5223,307144,6807702,0,0,0,0,0.0,56700.0
5224,307214,5971671,0,0,0,0,0.0,50904.0
5225,307347,5369543,0,0,0,0,0.0,495000.0

In [46]:
bureau_bad_debt['BAD_DEBT_LAST_365_DAYS'] = np.where(bureau_bad_debt['DAYS_CREDIT'].values >= -365, 1, 0)
bureau_bad_debt['BAD_DEBT_LAST_730_DAYS'] = np.where(bureau_bad_debt['DAYS_CREDIT'].values >= -730, 1, 0)

bureau_bad_debt['BAD_DEBT_FINISHED'] = np.where(bureau_bad_debt['DAYS_ENDDATE_FACT'].isnull(), 0, 1)
bureau_bad_debt['BAD_DEBT_DURATION'] = (bureau_bad_debt['DAYS_ENDDATE_FACT'] - bureau_bad_debt['DAYS_CREDIT']) * bureau_bad_debt['BAD_DEBT_FINISHED']

C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\441610481.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_bad_debt['BAD_DEBT_LAST_365_DAYS'] = np.where(bureau_bad_debt['DAYS_CREDIT'].values >= -365, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\441610481.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_bad_debt['BAD_DEBT_LAST_730_DAYS'] = np.where(bureau_bad_debt['DAYS_CREDIT'].values >= -730, 1, 0)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\441610481.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_bad_debt['BAD_DEBT_FINISHED'] = np.where(bureau_bad_debt['DAYS_ENDDATE_FACT'].isnull(), 0, 1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_37432\441610481.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_bad_debt['BAD_DEBT_DURATION'] = (bureau_bad_debt['DAYS_ENDDATE_FACT'] - bureau_bad_debt['DAYS_CREDIT']) * bureau_bad_debt['BAD_DEBT_FINISHED']

In [48]:
gb_bureau_bad_debt = bureau_bad_debt.groupby('SK_ID_CURR').agg({'SK_ID_BUREAU':'sum', 'BAD_DEBT_LAST_365_DAYS': 'sum', 'BAD_DEBT_LAST_730_DAYS': 'sum', 'BAD_DEBT_FINISHED': 'sum', 'BAD_DEBT_DURATION':'sum', 'AMT_CREDIT_SUM':'sum','AMT_CREDIT_SUM_DEBT': 'sum' }).reset_index()
gb_bureau_bad_debt.rename(columns={'AMT_CREDIT_SUM':'BAD_DEBT_SUM_CREDIT', 'AMT_CREDIT_SUM_DEBT':'BAD_DEBT_SUM_DEBT', 'SK_ID_BUREAU':'COUNT_BAD_DEBT'}, inplace=True)

In [49]:
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_active_count, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_close_count, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_sold, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_bad_debt, on='SK_ID_CURR', how='left')

gb_bureau_general.head()

,SK_ID_CURR,SK_ID_BUREAU,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,AMT_CREDIT_SUM_LIMIT,AMT_ANNUITY,CREDIT_CURRENCY,CREDIT_TYPE,CREDIT_ACTIVE,...,SOLD_FINISHED,SOLD_DURATION,SOLD_SUM_CREDIT,COUNT_BAD_DEBT,BAD_DEBT_LAST_365_DAYS,BAD_DEBT_LAST_730_DAYS,BAD_DEBT_FINISHED,BAD_DEBT_DURATION,BAD_DEBT_SUM_CREDIT,BAD_DEBT_SUM_DEBT
0,0,1,85513.50,77566.5,0.0,NaN,0.0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,28350.00,0.0,0.0,0.0,0.0,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6,254341.08,96417.0,0.0,0.0,0.0,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,7,483952.50,198769.5,0.0,0.0,0.0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6,2822544.00,1254505.5,0.0,0.0,0.0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
bureau_balance = pd.read_csv('../data/dseb63_bureau_balance_aggregated.csv')

In [53]:
bureau_balance

,SK_ID_BUREAU,C Last 12 Month,X Last 12 Month,0 Last 12 Month,Other Last 12 Month,MAX_MONTHS_BALANCE,TOTAL_MONTHS,Ratio C,Ratio X,Ratio 0,Ratio Other
0,5001718,3,2,6,2,0,39,0.076923,0.256410,0.615385,2
1,5001844,13,0,0,0,0,48,0.333333,0.250000,0.395833,1
2,5001922,13,0,0,0,0,36,0.527778,0.250000,0.194444,1
3,5001981,13,0,0,0,0,67,0.895522,0.014925,0.044776,3
4,5001988,5,2,6,0,0,53,0.094340,0.283019,0.603774,1
...,...,...,...,...,...,...,...,...,...,...,...
20699,6842759,13,0,0,0,0,74,0.581081,0.121622,0.108108,14
20700,6842765,13,0,0,0,0,49,0.428571,0.183673,0.367347,1
20701,6842791,13,0,0,0,0,53,0.754717,0.150943,0.056604,2
20702,6842874,13,0,0,0,0,90,0.888889,0.011111,0.088889,1
20703,6842880,13,0,0,0,0,58,0.620690,0.224138,0.120690,2

In [54]:
bureau_balance = pd.merge(bureau_balance, bureau[['SK_ID_CURR', 'SK_ID_BUREAU']], on='SK_ID_BUREAU', how='left')

In [55]:
bureau_balance

,SK_ID_BUREAU,C Last 12 Month,X Last 12 Month,0 Last 12 Month,Other Last 12 Month,MAX_MONTHS_BALANCE,TOTAL_MONTHS,Ratio C,Ratio X,Ratio 0,Ratio Other,SK_ID_CURR
0,5001718,3,2,6,2,0,39,0.076923,0.256410,0.615385,2,NaN
1,5001844,13,0,0,0,0,48,0.333333,0.250000,0.395833,1,NaN
2,5001922,13,0,0,0,0,36,0.527778,0.250000,0.194444,1,NaN
3,5001981,13,0,0,0,0,67,0.895522,0.014925,0.044776,3,NaN
4,5001988,5,2,6,0,0,53,0.094340,0.283019,0.603774,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
20699,6842759,13,0,0,0,0,74,0.581081,0.121622,0.108108,14,65279.0
20700,6842765,13,0,0,0,0,49,0.428571,0.183673,0.367347,1,297734.0
20701,6842791,13,0,0,0,0,53,0.754717,0.150943,0.056604,2,161515.0
20702,6842874,13,0,0,0,0,90,0.888889,0.011111,0.088889,1,87363.0
20703,6842880,13,0,0,0,0,58,0.620690,0.224138,0.120690,2,195427.0

In [ ]:
bureau_balance.dropna(subset=['SK_ID_CURR'], inplace=True)

In [58]:
bureau_balance['SK_ID_CURR'].nunique()

8196

In [60]:
gb_bureau_balance = bureau_balance.groupby('SK_ID_CURR').agg({'C Last 12 Month':'sum', 'X Last 12 Month':'sum', '0 Last 12 Month':'sum', 'Other Last 12 Month' : 'sum', 'MAX_MONTHS_BALANCE':'max','TOTAL_MONTHS':'sum', 'Ratio C':'mean' , 'Ratio X':'mean', 'Ratio 0':'mean'}).reset_index()

In [62]:
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_balance, on='SK_ID_CURR', how='left')

In [50]:
gb_bureau_general.to_csv('../data/dseb63_bureau_general_v2.csv', index=False)

In [63]:
gb_bureau_general

,SK_ID_CURR,SK_ID_BUREAU,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,AMT_CREDIT_SUM_LIMIT,AMT_ANNUITY,CREDIT_CURRENCY,CREDIT_TYPE,CREDIT_ACTIVE,...,BAD_DEBT_SUM_DEBT,C Last 12 Month,X Last 12 Month,0 Last 12 Month,Other Last 12 Month,MAX_MONTHS_BALANCE,TOTAL_MONTHS,Ratio C,Ratio X,Ratio 0
0,0,1,85513.50,77566.5,0.0,NaN,0.000,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,28350.00,0.0,0.0,0.0000,0.000,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6,254341.08,96417.0,0.0,0.0000,0.000,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,7,483952.50,198769.5,0.0,0.0000,0.000,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6,2822544.00,1254505.5,0.0,0.0000,0.000,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263486,307504,4,866153.25,119767.5,0.0,0.0000,0.000,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263487,307505,2,3618000.00,0.0,0.0,540000.0000,180927.000,1,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263488,307506,4,259263.00,0.0,0.0,0.0000,0.000,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263489,307508,7,5506306.83,251748.0,0.0,300.7875,25476.255,1,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263490,307509,2,315000.00,27900.0,0.0,0.0000,0.000,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN