In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [3]:
bureau_balance = pd.read_csv('../data/bureau_balance.csv')

In [4]:
bureau_balance

          SK_ID_BUREAU  MONTHS_BALANCE STATUS
0              5715448               0      C
1              5715448              -1      C
2              5715448              -2      C
3              5715448              -3      C
4              5715448              -4      C
...                ...             ...    ...
27299920       5041336             -47      X
27299921       5041336             -48      X
27299922       5041336             -49      X
27299923       5041336             -50      X
27299924       5041336             -51      X

[27299925 rows x 3 columns]

### Feature to get

- Duration(mean)
- Total payment
- Last balance
- Count C, 0, X
- % C in last 10 
- % X in last 10

In [5]:
bureau_balance['STATUS'].value_counts()

STATUS
C    13646993
0     7499507
X     5810482
1      242347
5       62406
2       23419
3        8924
4        5847
Name: count, dtype: int64

In [17]:
sample = bureau_balance[bureau_balance['SK_ID_BUREAU'] == 5714717]
sample

Empty DataFrame
Columns: [SK_ID_BUREAU, MONTHS_BALANCE, STATUS]
Index: []

Only for active account

In [19]:
appl_train = pd.read_csv('../data/application_train.csv')
bureau = pd.read_csv('../data/bureau.csv')
bureau = pd.merge(bureau[['SK_ID_CURR', 'SK_ID_BUREAU']], appl_train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')

In [20]:
bureau_balance = pd.merge(bureau_balance, bureau, on='SK_ID_BUREAU', how='left')
bureau_balance

          SK_ID_BUREAU  MONTHS_BALANCE STATUS  SK_ID_CURR  TARGET
0              5715448               0      C    380361.0     0.0
1              5715448              -1      C    380361.0     0.0
2              5715448              -2      C    380361.0     0.0
3              5715448              -3      C    380361.0     0.0
4              5715448              -4      C    380361.0     0.0
...                ...             ...    ...         ...     ...
27299920       5041336             -47      X    101874.0     1.0
27299921       5041336             -48      X    101874.0     1.0
27299922       5041336             -49      X    101874.0     1.0
27299923       5041336             -50      X    101874.0     1.0
27299924       5041336             -51      X    101874.0     1.0

[27299925 rows x 5 columns]

In [22]:
bureau_balance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27299925 entries, 0 to 27299924
Data columns (total 5 columns):
 #   Column          Dtype
---  ------          -----
 0   SK_ID_BUREAU    int64
 1   MONTHS_BALANCE  int64
 2   STATUS          object
 3   SK_ID_CURR      float64
 4   TARGET          float64
dtypes: float64(2), int64(2), object(1)
memory usage: 1.0+ GB

In [23]:
bureau_balance_positive = bureau_balance[bureau_balance['TARGET'] == 1]

In [25]:
bureau_balance_positive.groupby('SK_ID_BUREAU').agg({'STATUS': 'first', 'MONTHS_BALANCE': 'max'})

             STATUS  MONTHS_BALANCE
SK_ID_BUREAU
5008873           C               0
5008874           C               0
5008875           C               0
5008876           C               0
5008877           C               0
...             ...             ...
6841952           X             -58
6841953           X             -51
6841954           X             -51
6841955           X             -25
6841956           0               0

[43311 rows x 2 columns]