In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [3]:
pos_cash = pd.read_csv('../data/POS_CASH_balance.csv')

In [4]:
pos_cash.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,1803195,182943,-31,48.0,45.0,Active,0,0
1,1715348,367990,-33,36.0,35.0,Active,0,0
2,1784872,397406,-32,12.0,9.0,Active,0,0
3,1903291,269225,-35,48.0,42.0,Active,0,0
4,2341044,334279,-35,36.0,35.0,Active,0,0

In [6]:
pos_cash['SK_ID_PREV'].nunique()

936325

In [7]:
pos_cash['SK_ID_CURR'].value_counts()

SK_ID_CURR
265042    295
172612    247
309133    246
127659    245
185185    245
         ...
406557      1
240277      1
177557      1
251697      1
144536      1
Name: count, Length: 337252, dtype: int64

In [9]:
sample =  pos_cash[pos_cash['SK_ID_CURR'] == 265042]
sample

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
46847,2605449,265042,-20,6.0,0.0,Completed,0,0
79133,1776290,265042,-13,36.0,15.0,Active,0,0
168456,1130567,265042,-12,12.0,4.0,Active,0,0
268199,2244271,265042,-14,18.0,13.0,Active,0,0
301477,2567558,265042,-38,12.0,11.0,Active,0,0
...,...,...,...,...,...,...,...,...
9867214,1295332,265042,-90,15.0,15.0,Signed,0,0
9921816,1162724,265042,-54,16.0,0.0,Completed,0,0
9949110,2372251,265042,-60,18.0,4.0,Active,0,0
9949298,2372251,265042,-68,18.0,12.0,Active,0,0
9968398,1162724,265042,-55,16.0,1.0,Active,0,0

In [13]:
pos_cash.shape

(10001358, 8)

In [12]:
sample.sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'], ascending=False, inplace=True)
sample

C:\Users\Admin\AppData\Local\Temp\ipykernel_16912\3119951421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample.sort_values(by=['SK_ID_PREV','MONTHS_BALANCE'], ascending=False, inplace=True)

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,CNT_INSTALMENT,CNT_INSTALMENT_FUTURE,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
46847,2605449,265042,-20,6.0,0.0,Completed,0,0
2413621,2605449,265042,-21,6.0,1.0,Active,0,0
3901257,2605449,265042,-22,6.0,2.0,Active,0,0
1188043,2605449,265042,-23,6.0,3.0,Active,0,0
7990311,2605449,265042,-24,6.0,4.0,Active,0,0
...,...,...,...,...,...,...,...,...
3569734,1130567,265042,-16,12.0,8.0,Active,0,0
2240799,1130567,265042,-17,12.0,9.0,Active,0,0
9081101,1130567,265042,-18,12.0,10.0,Active,0,0
3381918,1130567,265042,-19,12.0,11.0,Active,0,0
2742694,1130567,265042,-20,12.0,12.0,Active,0,0