In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [16]:
previous_application = pd.read_csv('../data/dseb63_previous_application.csv')

In [9]:
display_missing_data_info(previous_application)

                           Missing Values  Percentage (%)
RATE_INTEREST_PRIMARY             1408910       99.661102
RATE_INTEREST_PRIVILEGED          1408910       99.661102
AMT_DOWN_PAYMENT                   749540       53.019698
RATE_DOWN_PAYMENT                  749540       53.019698
NAME_TYPE_SUITE                    694672       49.138538
DAYS_FIRST_DRAWING                 561106       39.690571
DAYS_FIRST_DUE                     561106       39.690571
DAYS_LAST_DUE_1ST_VERSION          561106       39.690571
DAYS_LAST_DUE                      561106       39.690571
DAYS_TERMINATION                   561106       39.690571
NFLAG_INSURED_ON_APPROVAL          561106       39.690571
AMT_GOODS_PRICE                    319525       22.602021
AMT_ANNUITY                        307218       21.731469
CNT_PAYMENT                        307213       21.731116
PRODUCT_COMBINATION                   313        0.022140
AMT_CREDIT                              1        0.000071

                           Missing Values  Percentage (%)
RATE_INTEREST_PRIMARY             1408910       99.661102
RATE_INTEREST_PRIVILEGED          1408910       99.661102
AMT_DOWN_PAYMENT                   749540       53.019698
RATE_DOWN_PAYMENT                  749540       53.019698
NAME_TYPE_SUITE                    694672       49.138538
DAYS_FIRST_DRAWING                 561106       39.690571
DAYS_FIRST_DUE                     561106       39.690571
DAYS_LAST_DUE_1ST_VERSION          561106       39.690571
DAYS_LAST_DUE                      561106       39.690571
DAYS_TERMINATION                   561106       39.690571
NFLAG_INSURED_ON_APPROVAL          561106       39.690571
AMT_GOODS_PRICE                    319525       22.602021
AMT_ANNUITY                        307218       21.731469
CNT_PAYMENT                        307213       21.731116
PRODUCT_COMBINATION                   313        0.022140
AMT_CREDIT                              1        0.000071

In [10]:
previous_application.head()

,SK_ID_PREV,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,FLAG_LAST_APPL_PER_CONTRACT,...,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL,SK_ID_CURR
0,2030495,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,Y,...,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0,293189
1,1696966,Consumer loans,68258.655,1800000.0,1754721.0,180000.0,1800000.0,SATURDAY,18,Y,...,36.0,low_normal,POS industry with interest,NaN,NaN,NaN,NaN,NaN,NaN,293189
2,2154916,Consumer loans,12417.390,108400.5,119848.5,0.0,108400.5,SUNDAY,14,Y,...,12.0,middle,POS industry with interest,365243.0,-512.0,-182.0,-392.0,-387.0,0.0,293189
3,2802425,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,Y,...,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0,91587
4,1536272,Cash loans,21709.125,450000.0,512370.0,NaN,450000.0,WEDNESDAY,9,Y,...,36.0,low_normal,Cash X-Sell: low,365243.0,-485.0,565.0,-155.0,-147.0,1.0,91587

In [11]:
previous_application['SK_ID_CURR'].nunique()

291057

In [ ]:

def previous_application_process(df_prev):


    

    # Separation of "WEEKDAY_APPR_PROCESS_START" variable into two categories as WEEK_DAY and WEEKEND

    df_prev["WEEKDAY_APPR_PROCESS_START"] = df_prev["WEEKDAY_APPR_PROCESS_START"].replace(['MONDAY','TUESDAY', 'WEDNESDAY','THURSDAY','FRIDAY'], 'WEEK_DAY')
    df_prev["WEEKDAY_APPR_PROCESS_START"] = df_prev["WEEKDAY_APPR_PROCESS_START"].replace(['SATURDAY', 'SUNDAY'], 'WEEKEND')

    # Separation of the "HOUR_APPR_PROCESS_START" variable into two categories: working_hours and off_hours
    a = [8,9,10,11,12,13,14,15,16,17]
    df_prev["HOUR_APPR_PROCESS_START"] = df_prev["HOUR_APPR_PROCESS_START"].replace(a, 'working_hours')

    b = [18,19,20,21,22,23,0,1,2,3,4,5,6,7]
    df_prev["HOUR_APPR_PROCESS_START"] = df_prev["HOUR_APPR_PROCESS_START"].replace(b, 'off_hours')


    # DAYS_DECISION values less than 1 year were given the value 1, and those greater than 1 year were given the value 0.
    df_prev["DAYS_DECISION"] = [1 if abs(i/(12*30)) <=1 else 0 for i in df_prev.DAYS_DECISION]

    # Separating the "NAME_TYPE_SUITE" variable into two categories as alone and not_alone

    df_prev["NAME_TYPE_SUITE"] = df_prev["NAME_TYPE_SUITE"].replace('Unaccompanied', 'alone')

    b = ['Family', 'Spouse, partner', 'Children', 'Other_B', 'Other_A', 'Group of people']
    df_prev["NAME_TYPE_SUITE"] = df_prev["NAME_TYPE_SUITE"].replace(b, 'not_alone')



    # These values in the "NAME_GOODS_CATEGORY" variable will be categorized as others
    a = ['Auto Accessories', 'Jewelry', 'Homewares', 'Medical Supplies', 'Vehicles', 'Sport and Leisure', 
         'Gardening', 'Other', 'Office Appliances', 'Tourism', 'Medicine', 'Direct Sales', 'Fitness', 'Additional Service', 
         'Education', 'Weapon', 'Insurance', 'House Construction', 'Animals'] 
    df_prev["NAME_GOODS_CATEGORY"] = df_prev["NAME_GOODS_CATEGORY"].replace(a, 'others')

    # "These values in the "NAME_SELLER_INDUSTRY" variable will be categorized as others
    a = ['Auto technology', 'Jewelry', 'MLM partners', 'Tourism'] 
    df_prev["NAME_SELLER_INDUSTRY"] = df_prev["NAME_SELLER_INDUSTRY"].replace(a, 'others')
    # Derives the variable containing the ratio of the loan requested to the loan granted
    df_prev["LOAN_RATE"] = df_prev.AMT_APPLICATION/df_prev.AMT_CREDIT

    # NEW VARIABLES

    # Derives the variable containing the ratio of the loan requested to the loan granted
    df_prev["NEW_LOAN_RATE"] = df_prev.AMT_APPLICATION/df_prev.AMT_CREDIT

    # The churn_prev variable is derived to indicate whether the payment date is late.
    # 1= delayed, 0 = not delayed, NaN = null
    k = df_prev.DAYS_LAST_DUE_1ST_VERSION - df_prev.DAYS_LAST_DUE
    df_prev["NEW_CHURN_PREV"] = [1 if i >= 0 else (0 if i < 0  else "NaN") for i in k]


    # NEW_INSURANCE variable has been defined to be used instead of NFLAG_INSURED_ON_APPROVAL variable.
    df_prev[(df_prev['AMT_CREDIT'] == 0) | (df_prev['AMT_GOODS_PRICE'] == 0)]['NEW_INSURANCE'] = np.nan
    df_prev['sigorta_miktari'] = df_prev['AMT_CREDIT'] - df_prev['AMT_GOODS_PRICE']
    df_prev["NEW_INSURANCE"] = df_prev['sigorta_miktari'].apply(lambda x: 1 if x > 0 else (0 if x <= 0 else np.nan))
    df_prev.drop('sigorta_miktari', axis=1, inplace=True)



# ADJUSTMENT_DIRECTION varible indicates whether the final credit amount is equal to clients' application  #PREV APPLICATION
    df_prev['AMT_DIFF_PERCENT'] = ((df_prev['AMT_CREDIT'] - df_prev['AMT_APPLICATION']) / df_prev['AMT_APPLICATION']) * 100
    df_prev['ADJUSTMENT_DIRECTION'] = (df_prev['AMT_CREDIT'] - df_prev['AMT_APPLICATION']) >= 0
    df_prev['ADJUSTMENT_DIRECTION'] = df_prev['ADJUSTMENT_DIRECTION'].map({'True': 1, 'False': 0})
#New features
    df_prev['PREVIOUS_TERM'] = df_prev['AMT_CREDIT'] / df_prev['AMT_ANNUITY']
    df_prev['PREVIOUS_AMT_TO_APPLICATION'] = df_prev['AMT_CREDIT'] / df_prev['AMT_APPLICATION']
    df_prev['PREVIOUS_CREDIT_TO_PRICE'] = df_prev['AMT_GOODS_PRICE'] / df_prev['AMT_CREDIT']
    df_prev['PREVIOUS_DAYSLASTDUE1ST_DAYSFIRSTDUE_DIFF'] = df_prev['DAYS_LAST_DUE_1ST_VERSION'] - df_prev['DAYS_FIRST_DUE']
    df_prev['PREVIOUS_DAYSLASTDUE_DAYSFIRSTDUE_DIFF'] = df_prev['DAYS_LAST_DUE'] - df_prev['DAYS_FIRST_DUE']
    df_prev['PREVIOUS_DAYSLASTDUE_DAYSLASTDUE1ST_DIFF'] = df_prev['DAYS_LAST_DUE'] - df_prev['DAYS_LAST_DUE_1ST_VERSION']
    
    
    #Interest rate
    df_prev['INTEREST'] = df_prev['CNT_PAYMENT']*df_prev['AMT_ANNUITY'] - df_prev['AMT_CREDIT']
    df_prev['INTEREST_RATE'] = 2*12*df_prev['INTEREST']/(df_prev['AMT_CREDIT']*(df_prev['CNT_PAYMENT']+1))
    df_prev['INTEREST_SHARE'] = df_prev['INTEREST']/df_prev['AMT_CREDIT']
    
    drop_list = ['AMT_DOWN_PAYMENT', 'SELLERPLACE_AREA', 'CNT_PAYMENT', 'PRODUCT_COMBINATION', 'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE','DAYS_LAST_DUE_1ST_VERSION', 'DAYS_LAST_DUE','DAYS_TERMINATION','NFLAG_INSURED_ON_APPROVAL']
    df_prev.drop(drop_list, axis = 1, inplace = True)

    # df_prev[df_prev['INTEREST_RATE']==-1]=np.nan It holds the names of categorical variables in the Previous table.
    category_columns=[]
    for i in df_prev.columns:
        if df_prev[i].dtypes == "O":
            category_columns.append(i)

    df_prev = pd.get_dummies(df_prev, columns = category_columns )

    prev_agg_list = {"SK_ID_CURR":["count"], 
                "AMT_ANNUITY":["max"],
                "AMT_APPLICATION":["min","mean","max"],
                "AMT_CREDIT":["max"], 
                "AMT_GOODS_PRICE":["sum", "mean"],
                "NFLAG_LAST_APPL_IN_DAY":["sum","mean"], 
                "RATE_DOWN_PAYMENT":["sum", "mean"],
                'AMT_DIFF_PERCENT':['max','min'],
                'ADJUSTMENT_DIRECTION':['max','min'],
                "RATE_INTEREST_PRIMARY":["sum", "mean"],
                "RATE_INTEREST_PRIVILEGED":["sum", "mean"],
                "DAYS_DECISION":["sum"],
                "NEW_LOAN_RATE":["sum", "mean", "min", "max"],
                "NEW_INSURANCE":["sum", "mean"],
                #"INTEREST_RATE":["sum", "mean", "min", "max"],
                "NAME_CONTRACT_TYPE_Cash loans":["sum", "mean"],
                "NAME_CONTRACT_TYPE_Consumer loans":["sum", "mean"],
                "NAME_CONTRACT_TYPE_Revolving loans":["sum", "mean"],
                "NAME_CONTRACT_TYPE_XNA":["sum", "mean"],
                "WEEKDAY_APPR_PROCESS_START_WEEKEND":["sum", "mean"],
                "WEEKDAY_APPR_PROCESS_START_WEEK_DAY":["sum", "mean"],
                "HOUR_APPR_PROCESS_START_off_hours":["sum", "mean"],
                "HOUR_APPR_PROCESS_START_working_hours":["sum", "mean"],
                "FLAG_LAST_APPL_PER_CONTRACT_N":["sum", "mean"],
                "FLAG_LAST_APPL_PER_CONTRACT_Y":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Building a house or an annex":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Business development":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Buying a garage":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Buying a home":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Buying a new car":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Buying a used car":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Car repairs":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Education":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Everyday expenses":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Furniture":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Gasification / water supply":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Hobby":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Journey":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Medicine":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Money for a third person":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Other":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Payments on other loans":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Refusal to name the goal":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Repairs":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Urgent needs":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_XAP":["sum", "mean"],
                "NAME_CASH_LOAN_PURPOSE_XNA":["sum", "mean"],
                "NAME_CONTRACT_STATUS_Approved":["sum", "mean"],
                "NAME_CONTRACT_STATUS_Canceled":["sum", "mean"],
                "NAME_CONTRACT_STATUS_Refused":["sum", "mean"],
                "NAME_CONTRACT_STATUS_Unused offer":["sum", "mean"],
                "NAME_PAYMENT_TYPE_Cash through the bank":["sum", "mean"],
                "NAME_PAYMENT_TYPE_Cashless from the account of the employer":["sum", "mean"],
                "NAME_PAYMENT_TYPE_Non-cash from your account":["sum", "mean"],
                "NAME_PAYMENT_TYPE_XNA":["sum", "mean"],
                "CODE_REJECT_REASON_CLIENT":["sum", "mean"],
                "CODE_REJECT_REASON_HC":["sum", "mean"],
                "CODE_REJECT_REASON_LIMIT":["sum", "mean"],
                "CODE_REJECT_REASON_SCO":["sum", "mean"],
                "CODE_REJECT_REASON_SCOFR":["sum", "mean"],
                "CODE_REJECT_REASON_SYSTEM":["sum", "mean"],
                "CODE_REJECT_REASON_VERIF":["sum", "mean"],
                "CODE_REJECT_REASON_XAP":["sum", "mean"],
                "CODE_REJECT_REASON_XNA":["sum", "mean"],
                "NAME_TYPE_SUITE_alone":["sum", "mean"],
                "NAME_TYPE_SUITE_not_alone":["sum", "mean"],
                "NAME_CLIENT_TYPE_New":["sum", "mean"],
                "NAME_CLIENT_TYPE_Refreshed":["sum", "mean"],
                "NAME_CLIENT_TYPE_Repeater":["sum", "mean"],
                "NAME_CLIENT_TYPE_XNA":["sum", "mean"],
                "NAME_GOODS_CATEGORY_Audio/Video":["sum", "mean"],
                "NAME_GOODS_CATEGORY_Clothing and Accessories":["sum", "mean"],
                "NAME_GOODS_CATEGORY_Computers":["sum", "mean"],
                "NAME_GOODS_CATEGORY_Construction Materials":["sum", "mean"],
                "NAME_GOODS_CATEGORY_Consumer Electronics":["sum", "mean"],
                "NAME_GOODS_CATEGORY_Furniture":["sum", "mean"],
                "NAME_GOODS_CATEGORY_Mobile":["sum", "mean"],
                "NAME_GOODS_CATEGORY_Photo / Cinema Equipment":["sum", "mean"],
                "NAME_GOODS_CATEGORY_XNA":["sum", "mean"],
                "NAME_GOODS_CATEGORY_others":["sum", "mean"],
                "NAME_PORTFOLIO_Cards":["sum", "mean"],
                "NAME_PORTFOLIO_Cars":["sum", "mean"],
                "NAME_PORTFOLIO_Cash":["sum", "mean"],
                "NAME_PORTFOLIO_POS":["sum", "mean"],
                "NAME_PORTFOLIO_XNA":["sum", "mean"],
                "NAME_PRODUCT_TYPE_XNA":["sum", "mean"],
                "NAME_PRODUCT_TYPE_walk-in":["sum", "mean"],
                "NAME_PRODUCT_TYPE_x-sell":["sum", "mean"],
                "CHANNEL_TYPE_AP+ (Cash loan)":["sum", "mean"],
                "CHANNEL_TYPE_Car dealer":["sum", "mean"],
                "CHANNEL_TYPE_Channel of corporate sales":["sum", "mean"],
                "CHANNEL_TYPE_Contact center":["sum", "mean"],
                "CHANNEL_TYPE_Country-wide":["sum", "mean"],
                "CHANNEL_TYPE_Credit and cash offices":["sum", "mean"],
                "CHANNEL_TYPE_Regional / Local":["sum", "mean"],
                "CHANNEL_TYPE_Stone":["sum", "mean"],
                "NAME_SELLER_INDUSTRY_Clothing":["sum", "mean"],
                "NAME_SELLER_INDUSTRY_Connectivity":["sum", "mean"],
                "NAME_SELLER_INDUSTRY_Construction":["sum", "mean"],
                "NAME_SELLER_INDUSTRY_Consumer electronics":["sum", "mean"],
                "NAME_SELLER_INDUSTRY_Furniture":["sum", "mean"],
                "NAME_SELLER_INDUSTRY_Industry":["sum", "mean"],
                "NAME_SELLER_INDUSTRY_XNA":["sum", "mean"],
                "NAME_SELLER_INDUSTRY_others":["sum", "mean"],
                "NAME_YIELD_GROUP_XNA":["sum", "mean"],
                "NAME_YIELD_GROUP_high":["sum", "mean"],
                "NAME_YIELD_GROUP_low_action":["sum", "mean"],
                "NAME_YIELD_GROUP_low_normal":["sum", "mean"],
                "NAME_YIELD_GROUP_middle":["sum", "mean"],
                "NEW_CHURN_PREV_0":["sum", "mean"],
                "NEW_CHURN_PREV_1":["sum", "mean"],
                "NEW_CHURN_PREV_NaN":["sum", "mean"],
                #New feat
                'PREVIOUS_TERM':['count', 'min','max'],
                'PREVIOUS_AMT_TO_APPLICATION':['count', 'min','max'],
                'PREVIOUS_CREDIT_TO_PRICE':['count', 'min','max'],
                'PREVIOUS_DAYSLASTDUE1ST_DAYSFIRSTDUE_DIFF':['count', 'min','max'],
                'PREVIOUS_DAYSLASTDUE_DAYSFIRSTDUE_DIFF' :['count', 'min','max'],
                'PREVIOUS_DAYSLASTDUE_DAYSLASTDUE1ST_DIFF':['count', 'min','max'],
                'INTEREST' :['count', 'min','max'],
                'INTEREST_RATE'   :['count', 'min','max'],  
                'INTEREST_SHARE':['count', 'min','max'] 
}
    
    
    
    return df_prev, prev_agg_list

In [18]:
df_prev,prev_agg_list  = previous_application_process(previous_application)

/tmp/ipykernel_113551/780908576.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_prev[(df_prev['AMT_CREDIT'] == 0) | (df_prev['AMT_GOODS_PRICE'] == 0)]['NEW_INSURANCE'] = np.nan

In [8]:
appl_train = pd.read_csv('../data/application_train.csv')

In [9]:
appl_train.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
previous_application.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
previous_application = pd.merge(previous_application, appl_train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')
previous_application.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL,TARGET
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0,0.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0,0.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0,0.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [12]:
previous_application_accept = previous_application[previous_application['NAME_CONTRACT_STATUS'] == 'Approved']
previous_application_accept.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL,TARGET
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0,0.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0,0.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0,0.0
5,1383531,199383,Cash loans,23703.930,315000.0,340573.5,NaN,315000.0,SATURDAY,8,...,18.0,low_normal,Cash X-Sell: low,365243.0,-654.0,-144.0,-144.0,-137.0,1.0,0.0

In [15]:
previous_application_accept['SK_ID_PREV'].nunique()

1036781

In [9]:
previous_application_accept.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY',
       'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE',
       'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START',
       'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY',
       'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY',
       'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE',
       'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE',
       'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE',
       'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE',
       'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY',
       'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION',
       'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL',
       'TARGET'],
      dtype='object')

- Rate down payment is percentage of downpayment. Drop the downpayment column
- Date = 365k mean life-time

In [10]:
previous_application_accept['NAME_CONTRACT_TYPE'].value_counts()

NAME_CONTRACT_TYPE
Consumer loans     626470
Cash loans         312540
Revolving loans     97771
Name: count, dtype: int64

In [12]:
previous_application_accept['NAME_GOODS_CATEGORY'].value_counts()

NAME_GOODS_CATEGORY
XNA                         410410
Mobile                      186174
Consumer Electronics        111525
Audio/Video                  89394
Computers                    88050
Furniture                    49090
Construction Materials       22471
Clothing and Accessories     21460
Photo / Cinema Equipment     21379
Auto Accessories              6560
Jewelry                       5679
Homewares                     4540
Medical Supplies              3539
Vehicles                      2990
Sport and Leisure             2718
Gardening                     2469
Other                         2432
Office Appliances             2082
Tourism                       1462
Medicine                      1448
Direct Sales                   372
Fitness                        207
Additional Service             116
Education                       91
Weapon                          70
Insurance                       52
Animals                          1
Name: count, dtype: int64

In [15]:
previous_application_ir = previous_application[previous_application['RATE_INTEREST_PRIMARY'].notnull()]

In [16]:
previous_application_ir

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL,TARGET
0,2030495,271877,Consumer loans,1730.430,17145.000,17145.0,0.000,17145.000,SATURDAY,15,...,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0,0.0
30,2138466,170289,Consumer loans,3286.485,32562.000,32562.0,0.000,32562.000,FRIDAY,12,...,12.0,middle,POS mobile with interest,365243.0,-273.0,57.0,-183.0,-179.0,0.0,0.0
506,1017424,250662,Consumer loans,6408.540,79372.215,63495.0,15877.215,79372.215,SUNDAY,16,...,12.0,middle,POS mobile with interest,365243.0,-100.0,230.0,-40.0,-37.0,0.0,0.0
598,2388655,414811,Consumer loans,14152.545,153387.000,138046.5,15340.500,153387.000,THURSDAY,9,...,12.0,middle,POS industry with interest,365243.0,-659.0,-329.0,-329.0,-323.0,0.0,0.0
659,1817104,332996,Consumer loans,1335.600,16279.290,13027.5,3251.790,16279.290,WEDNESDAY,13,...,12.0,middle,POS mobile with interest,365243.0,-220.0,110.0,-130.0,-123.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1666917,2062063,375705,Consumer loans,12356.730,136036.800,122428.8,13608.000,136036.800,WEDNESDAY,15,...,12.0,middle,POS mobile with interest,365243.0,-152.0,178.0,-152.0,-144.0,0.0,0.0
1666931,1087161,446465,Consumer loans,2507.085,21442.500,24840.0,0.000,21442.500,SATURDAY,11,...,12.0,middle,POS mobile with interest,365243.0,-130.0,200.0,-100.0,-93.0,0.0,0.0
1667362,1564508,334457,Consumer loans,3878.325,42458.355,38214.0,4244.355,42458.355,MONDAY,13,...,12.0,middle,POS mobile with interest,365243.0,-656.0,-326.0,-566.0,-559.0,0.0,NaN
1668649,2238210,409807,Consumer loans,5959.350,59044.500,59044.5,0.000,59044.500,SATURDAY,4,...,12.0,middle,POS mobile with interest,365243.0,-118.0,212.0,365243.0,365243.0,0.0,0.0
1669923,1465370,413210,Consumer loans,2380.860,23589.000,23589.0,0.000,23589.000,MONDAY,16,...,12.0,middle,POS mobile with interest,365243.0,-74.0,256.0,365243.0,365243.0,0.0,0.0

Day first due vs last due

Thường first due + last due_v1 = 365

last_due > 0 la chua tra no

In [18]:
previous_application_on_due = previous_application[previous_application['DAYS_LAST_DUE']> 0]

In [ ]:
previous_application_revolving = previous_application[previous_application['NAME_CONTRACT_TYPE'] == 'Revolving loans']
previous_application_revolving

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL,TARGET
17,1285768,142748,Revolving loans,9000.0,180000.0,180000.0,NaN,180000.0,FRIDAY,13,...,0.0,XNA,Card X-Sell,-277.0,-257.0,365243.0,365243.0,365243.0,0.0,NaN
34,1629736,255331,Revolving loans,10125.0,202500.0,202500.0,NaN,202500.0,SATURDAY,14,...,0.0,XNA,Card X-Sell,-265.0,-234.0,365243.0,365243.0,365243.0,0.0,0.0
45,2621158,281470,Revolving loans,14625.0,292500.0,292500.0,NaN,292500.0,FRIDAY,17,...,0.0,XNA,Card X-Sell,NaN,NaN,NaN,NaN,NaN,NaN,0.0
49,1371540,200721,Revolving loans,11250.0,225000.0,225000.0,NaN,225000.0,FRIDAY,15,...,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,-171.0,0.0,0.0
50,2261993,299391,Revolving loans,NaN,0.0,0.0,NaN,NaN,FRIDAY,13,...,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1669960,1731392,180860,Revolving loans,11250.0,0.0,225000.0,NaN,NaN,TUESDAY,17,...,0.0,XNA,Card X-Sell,-1083.0,-1055.0,365243.0,-354.0,365243.0,0.0,0.0
1669962,2017672,268190,Revolving loans,22500.0,0.0,450000.0,NaN,NaN,FRIDAY,18,...,0.0,XNA,Card X-Sell,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1670191,1755809,122569,Revolving loans,2250.0,45000.0,45000.0,NaN,45000.0,WEDNESDAY,12,...,0.0,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1670192,2101747,339383,Revolving loans,3375.0,0.0,67500.0,NaN,NaN,FRIDAY,18,...,0.0,XNA,Card X-Sell,-474.0,-438.0,365243.0,365243.0,365243.0,0.0,0.0
1670193,1120445,179433,Revolving loans,NaN,0.0,0.0,NaN,NaN,SUNDAY,13,...,NaN,XNA,Card Street,NaN,NaN,NaN,NaN,NaN,NaN,1.0

:

Accepted Revolving loans more likely to cancel, unless pay in ful

In [17]:
previous_application_no_first_due = previous_application[previous_application['DAYS_FIRST_DUE'] > 0]
previous_application_no_first_due

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL,TARGET
49,1371540,200721,Revolving loans,11250.000,225000.0,225000.0,NaN,225000.0,FRIDAY,15,...,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,-171.0,0.0,0.0
138,1897668,205582,Revolving loans,2250.000,45000.0,45000.0,NaN,45000.0,MONDAY,16,...,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,365243.0,0.0,0.0
143,1975174,276237,Revolving loans,22500.000,0.0,450000.0,NaN,NaN,TUESDAY,13,...,0.0,XNA,Card X-Sell,365243.0,365243.0,365243.0,365243.0,365243.0,0.0,0.0
150,1642964,248217,Consumer loans,18553.725,180000.0,194031.0,4500.0,180000.0,WEDNESDAY,12,...,12.0,low_normal,POS industry with interest,365243.0,365243.0,344.0,365243.0,365243.0,1.0,0.0
159,1723023,337203,Revolving loans,2250.000,45000.0,45000.0,NaN,45000.0,WEDNESDAY,10,...,0.0,XNA,Card Street,365243.0,365243.0,365243.0,365243.0,365243.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1669538,2572617,433117,Revolving loans,19125.000,382500.0,382500.0,NaN,382500.0,THURSDAY,11,...,0.0,XNA,Card X-Sell,-54.0,365243.0,365243.0,365243.0,365243.0,0.0,NaN
1669624,2461763,308500,Revolving loans,0.000,0.0,0.0,NaN,NaN,SUNDAY,4,...,0.0,XNA,Card Street,-1534.0,365243.0,365243.0,365243.0,-1172.0,0.0,0.0
1669730,2334397,440945,Revolving loans,11250.000,0.0,225000.0,NaN,NaN,FRIDAY,11,...,0.0,XNA,Card X-Sell,-589.0,365243.0,365243.0,365243.0,365243.0,0.0,0.0
1669796,1161466,134972,Revolving loans,4500.000,90000.0,90000.0,NaN,90000.0,TUESDAY,12,...,0.0,XNA,Card X-Sell,365243.0,365243.0,365243.0,365243.0,-195.0,0.0,NaN
1670199,1077969,242303,Consumer loans,8546.940,37926.0,40932.0,0.0,37926.0,THURSDAY,12,...,6.0,high,POS mobile with interest,365243.0,365243.0,174.0,365243.0,365243.0,1.0,1.0