In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

# BUREAU

## GROUP BY method

1. Groupby general data
2. Groupby with active accounts
3. Groupby with closed accounts
4. Groupby with sold and bad-debt accounts

Aggregate the bureau data with bureau_balance data.

In [2]:
def display_missing_data_info(dataframe, ascending=False):
    missing_values_count = dataframe.isnull().sum()
    missing_values_percentage = (dataframe.isnull().mean() * 100)
    missing_data = pd.DataFrame({
        'Missing Values': missing_values_count,
        'Percentage (%)': missing_values_percentage
    })
    
    missing_data = missing_data[missing_data['Missing Values'] > 0]
    
    sorted_missing_data = missing_data.sort_values(by='Missing Values', ascending=ascending)

    print(sorted_missing_data)
    return sorted_missing_data

In [3]:
bureau = pd.read_csv('../../data/dseb63_bureau.csv')

In [4]:
bureau[bureau['DAYS_CREDIT_ENDDATE'] < -40000]

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY,SK_ID_CURR
64127,5007091,Active,currency 1,-388,0,-41847.0,NaN,0.00,0,225000.0,0.00,225000.00,0.0,Credit card,-241,NaN,32911
104754,5612278,Closed,currency 1,-2796,0,-41821.0,-672.0,0.00,0,0.0,0.00,0.00,0.0,Credit card,-672,NaN,48631
123628,6540711,Closed,currency 1,-2317,0,-41824.0,-428.0,8271.99,0,0.0,0.00,0.00,0.0,Credit card,-428,NaN,252767
130195,6585564,Closed,currency 1,-2579,0,-41836.0,-687.0,0.00,0,0.0,0.00,0.00,0.0,Credit card,-687,NaN,277305
158489,5225714,Active,currency 1,-2571,0,-41862.0,NaN,0.00,0,202500.0,172003.68,30496.32,0.0,Credit card,-212,NaN,195866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410891,5989962,Closed,currency 1,-2821,0,-41846.0,-450.0,0.00,0,0.0,0.00,0.00,0.0,Credit card,-450,NaN,191134
1414842,5751553,Closed,currency 1,-2882,0,-41871.0,-475.0,0.00,0,0.0,0.00,0.00,0.0,Credit card,-475,NaN,293239
1418158,5755454,Active,currency 1,-2686,0,-41869.0,NaN,0.00,0,0.0,0.00,0.00,0.0,Credit card,-232,NaN,169403
1451455,6649929,Closed,currency 1,-2783,0,-41823.0,-674.0,0.00,0,0.0,0.00,0.00,0.0,Credit card,-674,NaN,14301
1459405,5571289,Closed,currency 1,-2252,0,-41846.0,-457.0,10323.36,0,0.0,0.00,0.00,0.0,Credit card,-457,NaN,181809

In [5]:
appl_train = pd.read_csv('../../data/dseb63_application_train.csv')
bureau = pd.merge(bureau, appl_train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')

In [6]:
bureau['DAYS_CREDIT_ENDDATE'][bureau['DAYS_CREDIT_ENDDATE'] < -40000] = np.nan
bureau['DAYS_CREDIT_UPDATE'][bureau['DAYS_CREDIT_UPDATE'] < -40000] = np.nan
bureau['DAYS_ENDDATE_FACT'][bureau['DAYS_ENDDATE_FACT'] < -40000] = np.nan

/tmp/ipykernel_1745290/1569320394.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  bureau['DAYS_CREDIT_ENDDATE'][bureau['DAYS_CREDIT_ENDDATE'] < -40000] = np.nan
/tmp/ipykernel_1745290/1569320394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau['DAYS_CREDIT_ENDDATE'][bureau['DAYS_CREDIT_ENDDATE'] < -40000] = np.nan
/tmp/ipykernel_1745290/1569320394.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  bureau['DAYS_CREDIT_UPDATE'][bureau['DAYS_CREDIT_UPDATE'] < -40000] = np.nan
/tmp/ipykernel_1745290/1569320394.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau['DAYS_CREDIT_UPDATE'][bureau['DAYS_CREDIT_UPDATE'] < -40000] = np.nan
/tmp/ipykernel_1745290/1569320394.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  bureau['DAYS_ENDDATE_FACT'][bureau['DAYS_ENDDATE_FACT'] < -40000] = np.nan
/tmp/ipykernel_1745290/1569320394.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau['DAYS_ENDDATE_FACT'][bureau['DAYS_ENDDATE_FACT'] < -40000] = np.nan

In [7]:
bureau['CREDIT_TYPE'].value_counts()

CREDIT_TYPE
Consumer credit                                 1069610
Credit card                                      343853
Car loan                                          23757
Mortgage                                          15607
Microloan                                          9005
Loan for business development                      1721
Another type of loan                                854
Unknown type of loan                                472
Loan for working capital replenishment              377
Real estate loan                                     23
Cash loan (non-earmarked)                            23
Loan for the purchase of equipment                   17
Loan for purchase of shares (margin lending)          4
Mobile operator loan                                  1
Interbank credit                                      1
Name: count, dtype: int64

In [8]:
bureau['CREDIT_TYPE'].value_counts()

CREDIT_TYPE
Consumer credit                                 1069610
Credit card                                      343853
Car loan                                          23757
Mortgage                                          15607
Microloan                                          9005
Loan for business development                      1721
Another type of loan                                854
Unknown type of loan                                472
Loan for working capital replenishment              377
Real estate loan                                     23
Cash loan (non-earmarked)                            23
Loan for the purchase of equipment                   17
Loan for purchase of shares (margin lending)          4
Mobile operator loan                                  1
Interbank credit                                      1
Name: count, dtype: int64

### PA feat

In [11]:
bureau['AMT_CREDIT_SUM'].fillna(0, inplace=True)

/tmp/ipykernel_1745290/4146824112.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bureau['AMT_CREDIT_SUM'].fillna(0, inplace=True)

In [12]:
mask_active = bureau['CREDIT_ACTIVE'] == 'Active'
mask_sold = bureau['CREDIT_ACTIVE'] == 'Sold'
mask_bad_debt = bureau['CREDIT_ACTIVE'] == 'Bad debt'

bureau.loc[mask_active | mask_sold | mask_bad_debt, 'DAYS_ENDDATE_FACT'] = 365243

bureau['AMT_CREDIT_SUM_DEBT'].fillna(0, inplace=True)
bureau['AMT_CREDIT_SUM_LIMIT'].fillna(0, inplace=True)
bureau['AMT_ANNUITY'].fillna(0, inplace=True)
bureau['AMT_CREDIT_MAX_OVERDUE'].fillna(0, inplace=True)

/tmp/ipykernel_1745290/3700598277.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bureau['AMT_CREDIT_SUM_DEBT'].fillna(0, inplace=True)
/tmp/ipykernel_1745290/3700598277.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bureau['AMT_CREDIT_SUM_LIMIT'].fillna(0, inplace=True)
/tmp/ipykernel_1745290/3700598277.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bureau['AMT_ANNUITY'].fillna(0, inplace=True)
/tmp/ipykernel_1745290/3700598277.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  bureau['AMT_CREDIT_MAX_OVERDUE'].fillna(0, inplace=True)

## ADD Features

In [13]:
bureau['CREDIT_DURATION'] = bureau['DAYS_CREDIT'] - bureau['DAYS_CREDIT_ENDDATE']
bureau['ENDDATE_DIF'] = bureau['DAYS_CREDIT_ENDDATE'] - bureau['DAYS_ENDDATE_FACT']
bureau['DEBT_PERCENTAGE'] = bureau['AMT_CREDIT_SUM'] / (bureau['AMT_CREDIT_SUM_DEBT'] + 1)
bureau['DEBT_CREDIT_DIFF'] = bureau['AMT_CREDIT_SUM'] - bureau['AMT_CREDIT_SUM_DEBT']
bureau['CREDIT_TO_ANNUITY_RATIO'] = bureau['AMT_CREDIT_SUM'] / (bureau['AMT_ANNUITY'] + 1)
bureau['BUREAU_CREDIT_DEBT_RATIO'] = bureau['AMT_CREDIT_SUM_DEBT'] / (bureau['AMT_CREDIT_SUM'] + 1) 

bureau['UTILIZATION_RATIO'] = bureau['AMT_CREDIT_SUM_DEBT'] / (bureau['AMT_CREDIT_SUM_LIMIT'] +1)

### Bureau 3.1: Mask the division by zero

In [14]:
bureau['DEBT_PERCENTAGE'] *= (bureau['AMT_CREDIT_SUM_DEBT'] !=0)
bureau['CREDIT_TO_ANNUITY_RATIO'] *= (bureau['AMT_ANNUITY'] !=0)
bureau['BUREAU_CREDIT_DEBT_RATIO'] *= (bureau['AMT_CREDIT_SUM'] !=0)
bureau['UTILIZATION_RATIO'] *= (bureau['AMT_CREDIT_SUM_LIMIT'] !=0)

mask_sum_debt = (bureau['AMT_CREDIT_SUM_DEBT'] ==0)
bureau.loc[mask_sum_debt, 'DEBT_PERCENTAGE'] = np.nan

mask_annuity = (bureau['AMT_ANNUITY'] ==0)
bureau.loc[mask_annuity, 'CREDIT_TO_ANNUITY_RATIO'] = np.nan

mask_credit_sum = (bureau['AMT_CREDIT_SUM'] ==0)
bureau.loc[mask_credit_sum, 'BUREAU_CREDIT_DEBT_RATIO'] = np.nan

mask_credit_sum_limit = (bureau['AMT_CREDIT_SUM_LIMIT'] ==0)
bureau.loc[mask_credit_sum_limit, 'UTILIZATION_RATIO'] = np.nan

bureau['DEBT_PERCENTAGE'] = bureau['DEBT_PERCENTAGE'].clip(-9,9)
bureau['CREDIT_TO_ANNUITY_RATIO'] = bureau['CREDIT_TO_ANNUITY_RATIO'].clip(-9,9)
bureau['BUREAU_CREDIT_DEBT_RATIO'] = bureau['BUREAU_CREDIT_DEBT_RATIO'].clip(-9,9)
bureau['UTILIZATION_RATIO'] = bureau['UTILIZATION_RATIO'].clip(-9,9)

In [15]:
one_hot_encoded = pd.get_dummies(bureau['CREDIT_TYPE'], prefix='CREDIT_TYPE')

## General
- Count record
- SUM overdue
- Count currency
- Sum credit
- Sum debt
- Sum overdue
- Count credit_type
- sum everything :))
- Credit sum on Car loan
- Credit sum on Consumer credit
- Credit sum on Credit Card
- Credit sum on Mortgage
- Credit sum on Other

In [16]:
bureau['UNPAID_CREDIT'] = np.where(bureau['DAYS_ENDDATE_FACT'].isnull(), 0, 1)

In [17]:
bureau['AMT_CREDIT_MEAN'] = bureau['AMT_CREDIT_SUM']
bureau['AMT_CREDIT_DEBT_MEAN'] = bureau['AMT_CREDIT_SUM_DEBT']

In [ ]:
gb_bureau_general = bureau.groupby('SK_ID_CURR').agg({'SK_ID_BUREAU': 'count',
                                                      'AMT_CREDIT_SUM': ['sum', 'mean', 'std'], 
                                                      'AMT_CREDIT_SUM_DEBT': ['sum', 'mean', 'std'],  
                                                      'AMT_CREDIT_SUM_OVERDUE': ['sum'], 
                                                      
                                                      'AMT_ANNUITY': ['sum', 'mean', 'std'], 
                                                       
                                                       # Check later (v3)
                                                      'CNT_CREDIT_PROLONG': [ 'mean'], 
                                                      'DAYS_CREDIT_UPDATE': ['mean', 'max'],
                                                      'CREDIT_DURATION': ['mean', 'std'],
                                                      'AMT_CREDIT_MAX_OVERDUE': ['sum', 'mean', 'std'],
                                                      'AMT_CREDIT_SUM_LIMIT':['sum', 'mean', 'std'], 
                                                      
                                                      # 'CREDIT_DURATION': 'mean',
                                                      # 'AMT_CREDIT_SUM_LIMIT':['mean', 'std'],
                                                      
                                                      # 'CREDIT_CURRENCY': 'nunique', 
                                                      'CREDIT_TYPE': 'nunique', 
                                                      'CREDIT_ACTIVE': 'nunique' ,
                                                      


                                                      'DAYS_CREDIT': ['min', 'max', 'mean', 'var'],
                                                      'ENDDATE_DIF': 'mean',
                                                        'DEBT_PERCENTAGE': ['mean','std'],
                                                        'DEBT_CREDIT_DIFF': ['mean','std'],

                                                          #v3
                                                        # 'CREDIT_TO_ANNUITY_RATIO': 'mean',
                                                        # 'BUREAU_CREDIT_DEBT_RATIO': 'mean',
                                                      
                                                      # v3.1
                                                      'CREDIT_TO_ANNUITY_RATIO': ['mean', 'var'],
                                                      'BUREAU_CREDIT_DEBT_RATIO': ['mean','var'],

                                                        'UTILIZATION_RATIO': ['mean', 'std']
                                                      }).reset_index()
gb_bureau_general.columns = ['GENERAL_'+'_'.join(col).strip() for col in gb_bureau_general.columns.values]


gb_bureau_general.rename(columns={'GENERAL_SK_ID_CURR_':'SK_ID_CURR'}, inplace=True)

gb_bureau_general['GENERAL_AVG_PAST_LOAN_PER_TYPE'] = gb_bureau_general['GENERAL_CREDIT_TYPE_nunique'] / gb_bureau_general['GENERAL_SK_ID_BUREAU_count'] * (gb_bureau_general['GENERAL_SK_ID_BUREAU_count'] != 0)


# Group by the loan type

others_loan = ['Another type of loan', 'Unknown type of loan', 'Loan for working capital replenishment', 'Cash loan (non-earmarked)', 'Real estate loan', 'Loan for the purchase of equipment', 'Mobile operator loan', 'Interbank credit', 'Loan for purchase of shares (margin lending)']
mapping_others_loan= {x: 'Others' for x in others_loan}
bureau['CREDIT_TYPE'] = bureau['CREDIT_TYPE'].replace(mapping_others_loan)

sum_on_car_loan = bureau[bureau['CREDIT_TYPE'] == 'Car loan'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum'}).reset_index()
sum_on_car_loan.rename(columns={'AMT_CREDIT_SUM':'SUM_CREDIT_CAR_LOAN'}, inplace=True)

sum_on_credit_card = bureau[bureau['CREDIT_TYPE'] == 'Credit card'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
sum_on_credit_card.rename(columns={'AMT_CREDIT_SUM':'SUM_CREDIT_CARD', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_CARD', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_CARD' }, inplace=True)

sum_on_mortgage = bureau[bureau['CREDIT_TYPE'] == 'Mortgage'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum'}).reset_index()
sum_on_mortgage.rename(columns={'AMT_CREDIT_SUM':'SUM_MORTGAGE', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_MORTGAGE' }, inplace=True)

sum_on_consumer_credit = bureau[bureau['CREDIT_TYPE'] == 'Consumer credit'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
sum_on_consumer_credit.rename(columns={'AMT_CREDIT_SUM':'SUM_CONSUMER_CREDIT', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_CONSUMER_CREDIT', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_CONSUMER_CREDIT' }, inplace=True)

sum_on_microloan = bureau[bureau['CREDIT_TYPE'] == 'Microloan'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum' }).reset_index()
sum_on_microloan.rename(columns={'AMT_CREDIT_SUM':'SUM_MICROLOAN', 'AMT_CREDIT_SUM_DEBT':'SUM_DEBT_MICROLOAN'}, inplace=True)

# sum_on_loan_for_business_development = bureau[bureau['CREDIT_TYPE'] == 'Loan for business development'].groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_OVERDUE': 'sum'}).reset_index()
# sum_on_loan_for_business_development.rename(columns={'AMT_CREDIT_SUM':'SUM_BUSINESS_DEVELOPMENT', 'AMT_CREDIT_SUM_OVERDUE':'SUM_OVERDUE_BUSINESS_DEVELOPMENT' }, inplace=True)

In [19]:
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_car_loan, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_credit_card, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_mortgage, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_consumer_credit, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, sum_on_microloan, on='SK_ID_CURR', how='left')
# gb_bureau_general = pd.merge(gb_bureau_general, sum_on_loan_for_business_development, on='SK_ID_CURR', how='left')
gb_bureau_general.head()

,SK_ID_CURR,GENERAL_SK_ID_BUREAU_count,GENERAL_AMT_CREDIT_SUM_sum,GENERAL_AMT_CREDIT_SUM_mean,GENERAL_AMT_CREDIT_SUM_std,GENERAL_AMT_CREDIT_SUM_DEBT_sum,GENERAL_AMT_CREDIT_SUM_DEBT_mean,GENERAL_AMT_CREDIT_SUM_DEBT_std,GENERAL_AMT_CREDIT_SUM_OVERDUE_sum,GENERAL_AMT_ANNUITY_sum,...,SUM_CREDIT_CARD,SUM_DEBT_CARD,SUM_OVERDUE_CARD,SUM_MORTGAGE,SUM_DEBT_MORTGAGE,SUM_CONSUMER_CREDIT,SUM_DEBT_CONSUMER_CREDIT,SUM_OVERDUE_CONSUMER_CREDIT,SUM_MICROLOAN,SUM_DEBT_MICROLOAN
0,0,1,85513.50,85513.500000,NaN,77566.5,77566.500000,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,85513.50,77566.5,0.0,NaN,NaN
1,1,1,28350.00,28350.000000,NaN,0.0,0.000000,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,28350.00,0.0,0.0,NaN,NaN
2,2,6,254341.08,42390.180000,27030.097199,96417.0,16069.500000,25705.163734,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,254341.08,96417.0,0.0,NaN,NaN
3,3,7,483952.50,69136.071429,41184.078332,198769.5,28395.642857,58477.076226,0.0,0.0,...,148500.0,157698.0,0.0,NaN,NaN,335452.50,41071.5,0.0,NaN,NaN
4,4,6,2822544.00,470424.000000,317857.683022,1254505.5,209084.250000,264456.157378,0.0,0.0,...,270000.0,261477.0,0.0,NaN,NaN,2552544.00,993028.5,0.0,NaN,NaN

Drop all the Duration < 0

In [20]:
bureau['DAYS_CREDIT_ENDDATE'] = bureau['DAYS_CREDIT_ENDDATE'].fillna(365243)
bureau['DURATION'] = bureau['DAYS_CREDIT_ENDDATE'] - bureau['DAYS_CREDIT']

In [21]:
# bureau = bureau[bureau['DURATION'] >= 0] v3.2

In [22]:
bureau_active = bureau[bureau['CREDIT_ACTIVE'] == 'Active']
bureau_active

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,...,ENDDATE_DIF,DEBT_PERCENTAGE,DEBT_CREDIT_DIFF,CREDIT_TO_ANNUITY_RATIO,BUREAU_CREDIT_DEBT_RATIO,UTILIZATION_RATIO,UNPAID_CREDIT,AMT_CREDIT_MEAN,AMT_CREDIT_DEBT_MEAN,DURATION
1,5714463,Active,currency 1,-208,0,1075.0,365243.0,0.0,0,225000.0,...,-364168.0,1.313155,53658.00,NaN,0.761517,NaN,1,225000.0,171342.00,1283.0
2,5714464,Active,currency 1,-203,0,528.0,365243.0,0.0,0,464323.5,...,-364715.0,NaN,464323.50,NaN,0.000000,NaN,1,464323.5,0.00,731.0
3,5714465,Active,currency 1,-203,0,365243.0,365243.0,0.0,0,90000.0,...,NaN,NaN,90000.00,NaN,0.000000,NaN,1,90000.0,0.00,365446.0
4,5714466,Active,currency 1,-629,0,1197.0,365243.0,77674.5,0,2700000.0,...,-364046.0,NaN,2700000.00,NaN,0.000000,NaN,1,2700000.0,0.00,1826.0
5,5714467,Active,currency 1,-273,0,27460.0,365243.0,0.0,0,180000.0,...,-337783.0,2.534555,108982.62,NaN,0.394539,0.651634,1,180000.0,71017.38,27733.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465310,5072148,Active,currency 1,-509,0,584.0,365243.0,0.0,0,391500.0,...,-364659.0,1.012555,4855.50,NaN,0.987595,NaN,1,391500.0,386644.50,1093.0
1465312,5099978,Active,currency 1,-27,0,399.0,365243.0,0.0,0,105543.0,...,-364844.0,0.819033,-23319.00,NaN,1.220932,NaN,1,105543.0,128862.00,426.0
1465314,5094072,Active,currency 1,-1119,0,-30.0,365243.0,0.0,0,270000.0,...,-365273.0,2.059717,138915.00,NaN,0.485498,NaN,1,270000.0,131085.00,1089.0
1465316,5044500,Active,currency 1,-420,0,676.0,365243.0,0.0,0,135000.0,...,-364567.0,1.349879,34992.00,9.0,0.740795,NaN,1,135000.0,100008.00,1096.0
1465322,5043236,Active,currency 1,-1441,0,2197.0,365243.0,0.0,0,1800000.0,...,-363046.0,1.671603,723190.50,NaN,0.598227,NaN,1,1800000.0,1076809.50,3638.0

### Feature for Active
- Count active
- Count active in 30 days
- Count active in 90 days
- Count active in 180 days
- Count active in 365 days
- Count Avaliable in next 30 days
- Count Avaliable in next 180 days
- Count active credit-type
- Count life-time duration

- Total debt in 30 days
- Total credit in 30 days
- Total debt in 180 days
- Total credit in 180 days
- Total debt in 365 days
- Total credit in 365 days

- Total credit life-time

- Average duration (not life-time)
- Sum annuity

In [23]:
def bureau_active_close_feat(bureau_active, status = 'ACTIVE'):    
    bureau_active["LAST_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -30, 1, 0)
    bureau_active["LAST_60_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -60, 1, 0)
    bureau_active["LAST_90_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -90, 1, 0)
    bureau_active["LAST_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -180, 1, 0)
    bureau_active["LAST_365_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -365, 1, 0)
    bureau_active["LAST_1000_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -1000, 1, 0)
    
    bureau_active["NEXT_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 30, 1, 0)
    bureau_active["NEXT_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 60, 1, 0)
    bureau_active["LIFE_TIME_CREDIT"] = np.where(bureau_active['DAYS_CREDIT_ENDDATE'] >= 16000, 1, 0)

    gb_bureau_active_count = bureau_active.groupby('SK_ID_CURR').agg({ 'SK_ID_BUREAU':'count', 
                                                                      'LAST_30_DAYS': 'sum', 
                                                                      'LAST_60_DAYS': 'sum', 
                                                                      'LAST_90_DAYS': 'sum', 
                                                                      'LAST_180_DAYS': 'sum', 
                                                                      'LAST_365_DAYS': 'sum', 
                                                                      'LAST_1000_DAYS':'sum', 
                                                                      'NEXT_30_DAYS': 'sum', 
                                                                      'NEXT_180_DAYS': 'sum', 
                                                                      'LIFE_TIME_CREDIT': 'sum', 
                                                                      'CREDIT_TYPE':'nunique', 
                                                                      'DAYS_CREDIT': 'max',
                                                                      
                                                                      'AMT_CREDIT_SUM':'sum', 
                                                                      'AMT_CREDIT_MEAN':'mean',
                                                                      'AMT_CREDIT_SUM_DEBT':'sum',
                                                                      
                                                                    'AMT_CREDIT_DEBT_MEAN':'mean',
                                                                      'AMT_CREDIT_SUM_LIMIT':'sum', 
                                                                      'AMT_ANNUITY':'sum'}).reset_index()
    gb_bureau_active_count.rename(columns={ 'SK_ID_BUREAU':status, 'LAST_30_DAYS':f'{status}_LAST_30_DAYS', 'LAST_60_DAYS':f'{status}_LAST_60_DAYS', 'LAST_90_DAYS':f'{status}_LAST_90_DAYS', 'LAST_180_DAYS':f'{status}_LAST_180_DAYS', 'LAST_365_DAYS':f'{status}_LAST_365_DAYS', 'LAST_1000_DAYS':f'{status}_LAST_1000_DAYS', 'NEXT_30_DAYS':f'{status}_NEXT_30_DAYS', 'NEXT_180_DAYS':f'{status}_NEXT_180_DAYS', 'LIFE_TIME_CREDIT':f'{status}_LIFE_TIME_CREDIT', 'CREDIT_TYPE':f'{status}_CREDIT_TYPE', 'AMT_CREDIT_SUM': f'{status}_AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_LIMIT':f'{status}_AMT_CREDIT_SUM_LIMIT', 'AMT_ANNUITY':f'{status}_AMT_ANNUITY', 'DAYS_CREDIT':f'{status}_DAYS_CREDIT' }, inplace=True)
    df_30_days = bureau_active[bureau_active['LAST_30_DAYS'] == 1].copy()
    gb_bureau_active_30_days = df_30_days.groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum'}).reset_index()
    gb_bureau_active_30_days.rename(columns={'AMT_CREDIT_SUM':f'{status}_SUM_CREDIT_30_DAYS'}, inplace=True)

    df_180_days = bureau_active[bureau_active['LAST_180_DAYS'] == 1].copy()
    gb_bureau_active_180_days = df_180_days.groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum'}).reset_index()
    gb_bureau_active_180_days.rename(columns={'AMT_CREDIT_SUM':f'{status}_SUM_CREDIT_180_DAYS', 'AMT_CREDIT_SUM_DEBT':f'{status}_SUM_DEBT_180_DAYS'}, inplace=True)


    df_life_time_credit = bureau_active[bureau_active['LIFE_TIME_CREDIT'] == 1].copy()
    
    if status == 'ACTIVE':
        gb_bureau_active_life_time_credit = df_life_time_credit.groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum', 'AMT_CREDIT_SUM_DEBT': 'sum'}).reset_index()
        gb_bureau_active_life_time_credit.rename(columns={'AMT_CREDIT_SUM':f'{status}_SUM_CREDIT_LIFE_TIME', 'AMT_CREDIT_SUM_DEBT':f'{status}_SUM_DEBT_LIFE_TIME'}, inplace=True)
    else:
        gb_bureau_active_life_time_credit = df_life_time_credit.groupby('SK_ID_CURR').agg({'AMT_CREDIT_SUM': 'sum',}).reset_index()
        gb_bureau_active_life_time_credit.rename(columns={'AMT_CREDIT_SUM':f'{status}_SUM_CREDIT_LIFE_TIME'}, inplace=True)

    df_not_life_time_credit = bureau_active[(bureau_active['LIFE_TIME_CREDIT'] == 0) & (bureau_active['DURATION'] >= 0)].copy()
    gb_bureau_active_not_life_time_credit = df_not_life_time_credit.groupby('SK_ID_CURR').agg({'DURATION':'mean'}).reset_index()
    gb_bureau_active_not_life_time_credit.rename(columns={'DURATION':f'{status}_MEAN_DURATION_NOT_LIFE_TIME'}, inplace=True)

    if status == 'ACTIVE':
       
        gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_30_days, on='SK_ID_CURR', how='left')
    gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_180_days, on='SK_ID_CURR', how='left')
    gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_life_time_credit, on='SK_ID_CURR', how='left')
    gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_not_life_time_credit, on='SK_ID_CURR', how='left')
    
    if status == 'CLOSE':
        
        gb_bureau_active_count.drop(columns=[f'{status}_NEXT_30_DAYS', f'{status}_NEXT_180_DAYS', f'{status}_LAST_30_DAYS', f'{status}_LAST_60_DAYS', f'{status}_SUM_DEBT_180_DAYS'], inplace=True)
        
        # Add latency here
        
        # df_not_life_time_credit['LATENCY_30_DAYS'] = df_not_life_time_credit['LATENCY']*df_not_life_time_credit["LAST_30_DAYS"]
        df_not_life_time_credit['LATENCY_180_DAYS'] = df_not_life_time_credit['LATENCY']*df_not_life_time_credit["LAST_180_DAYS"]
        df_not_life_time_credit['LATENCY_365_DAYS'] = df_not_life_time_credit['LATENCY']*df_not_life_time_credit["LAST_365_DAYS"]
        
        gb_bureau_active_latency = df_not_life_time_credit.groupby('SK_ID_CURR').agg({'LATENCY_180_DAYS':'sum', 'LATENCY_365_DAYS':'sum', 'LATENCY':'mean'}).reset_index()
        gb_bureau_active_latency.rename(columns={'LATENCY_180_DAYS':'CLOSE_LATENCY_180_DAYS', 'LATENCY_365_DAYS':'CLOSE_LATENCY_365_DAYS', 'LATENCY':'CLOSE_MEAN_LATENCY'}, inplace=True)
        gb_bureau_active_count = pd.merge(gb_bureau_active_count, gb_bureau_active_latency, on='SK_ID_CURR', how='left')
        
        gb_bureau_active_count['CLOSE_LATENCY_180_DAYS'] = gb_bureau_active_count['CLOSE_LATENCY_180_DAYS']/gb_bureau_active_count['CLOSE_LAST_180_DAYS']
        gb_bureau_active_count['CLOSE_LATENCY_365_DAYS'] = gb_bureau_active_count['CLOSE_LATENCY_365_DAYS']/gb_bureau_active_count['CLOSE_LAST_365_DAYS']
        
        # Add mask ??
    
    return gb_bureau_active_count

In [24]:
gb_bureau_active_count = bureau_active_close_feat(bureau_active, 'ACTIVE')

/tmp/ipykernel_1745290/2824271316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -30, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_60_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -60, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_90_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -90, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -180, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_365_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -365, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_1000_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -1000, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["NEXT_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 30, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["NEXT_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 60, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LIFE_TIME_CREDIT"] = np.where(bureau_active['DAYS_CREDIT_ENDDATE'] >= 16000, 1, 0)

In [25]:
gb_bureau_active_count

,SK_ID_CURR,ACTIVE,ACTIVE_LAST_30_DAYS,ACTIVE_LAST_60_DAYS,ACTIVE_LAST_90_DAYS,ACTIVE_LAST_180_DAYS,ACTIVE_LAST_365_DAYS,ACTIVE_LAST_1000_DAYS,ACTIVE_NEXT_30_DAYS,ACTIVE_NEXT_180_DAYS,...,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_DEBT_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT,ACTIVE_AMT_ANNUITY,ACTIVE_SUM_CREDIT_30_DAYS,ACTIVE_SUM_CREDIT_180_DAYS,ACTIVE_SUM_DEBT_180_DAYS,ACTIVE_SUM_CREDIT_LIFE_TIME,ACTIVE_SUM_DEBT_LIFE_TIME,ACTIVE_MEAN_DURATION_NOT_LIFE_TIME
0,0,1,0,0,1,1,1,1,1,1,...,77566.5,77566.5,0.000,0.00,NaN,85513.50,77566.5,NaN,NaN,300.000000
1,1,1,0,0,0,0,0,0,1,1,...,0.0,0.0,0.000,0.00,NaN,NaN,NaN,NaN,NaN,304.000000
2,2,2,1,2,2,2,2,2,2,2,...,96417.0,48208.5,0.000,0.00,37417.5,101272.50,96417.0,NaN,NaN,304.000000
3,3,3,0,0,0,1,2,3,3,3,...,198769.5,66256.5,0.000,0.00,NaN,44460.00,35527.5,NaN,NaN,636.666667
4,4,3,0,0,0,0,1,3,3,3,...,1254505.5,418168.5,0.000,0.00,NaN,NaN,NaN,NaN,NaN,1339.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217145,307501,1,0,0,0,0,0,1,1,1,...,2168721.0,2168721.0,0.000,0.00,NaN,NaN,NaN,NaN,NaN,4383.000000
217146,307504,1,0,0,0,0,0,1,1,1,...,119767.5,119767.5,0.000,0.00,NaN,NaN,NaN,NaN,NaN,1462.000000
217147,307505,2,0,0,0,1,1,2,2,2,...,0.0,0.0,540000.000,180927.00,NaN,3078000.00,0.0,NaN,NaN,6393.000000
217148,307508,4,0,0,0,1,3,4,4,4,...,251748.0,62937.0,1804.725,17434.17,NaN,104547.33,89635.5,13500.0,11691.0,776.000000
217149,307509,1,0,0,0,0,1,1,1,1,...,27900.0,27900.0,0.000,0.00,NaN,NaN,NaN,NaN,NaN,1318.000000

## Closed account

In [26]:
bureau_closed = bureau[bureau['CREDIT_ACTIVE'] == 'Closed']
bureau_closed

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,...,ENDDATE_DIF,DEBT_PERCENTAGE,DEBT_CREDIT_DIFF,CREDIT_TO_ANNUITY_RATIO,BUREAU_CREDIT_DEBT_RATIO,UTILIZATION_RATIO,UNPAID_CREDIT,AMT_CREDIT_MEAN,AMT_CREDIT_DEBT_MEAN,DURATION
0,5714462,Closed,currency 1,-497,0,-153.0,-153.0,0.0,0,91323.00,...,0.0,NaN,91323.00,NaN,0.0,NaN,1,91323.00,0.0,344.0
7,5714458,Closed,currency 1,-1872,0,-776.0,-1203.0,0.0,0,494550.00,...,427.0,NaN,494550.00,NaN,0.0,NaN,1,494550.00,0.0,1096.0
8,5714459,Closed,currency 1,-1734,0,-638.0,-1336.0,0.0,0,1084032.00,...,698.0,NaN,1084032.00,NaN,0.0,NaN,1,1084032.00,0.0,1096.0
9,5714460,Closed,currency 1,-1333,0,-1089.0,-987.0,0.0,0,102150.00,...,-102.0,NaN,102150.00,NaN,0.0,NaN,1,102150.00,0.0,244.0
10,5714461,Closed,currency 1,-1011,0,-830.0,-770.0,0.0,0,500463.00,...,-60.0,NaN,500463.00,NaN,0.0,NaN,1,500463.00,0.0,181.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465319,5052615,Closed,currency 1,-697,0,-577.0,-577.0,0.0,0,27169.92,...,0.0,NaN,27169.92,NaN,0.0,NaN,1,27169.92,0.0,120.0
1465320,5052629,Closed,currency 1,-532,0,45.0,-227.0,0.0,0,450000.00,...,272.0,NaN,450000.00,NaN,0.0,NaN,1,450000.00,0.0,577.0
1465321,5054382,Closed,currency 1,-381,0,-199.0,-199.0,0.0,0,19800.00,...,0.0,NaN,19800.00,NaN,0.0,NaN,1,19800.00,0.0,182.0
1465323,5053303,Closed,currency 1,-375,0,-41.0,-19.0,0.0,0,175054.50,...,-22.0,NaN,175054.50,9.0,0.0,NaN,1,175054.50,0.0,334.0
1465324,5053356,Closed,currency 1,-2724,0,-2511.0,-2511.0,0.0,0,101250.00,...,0.0,NaN,101250.00,NaN,0.0,NaN,1,101250.00,0.0,213.0

In [27]:
bureau_closed = bureau_closed[bureau_closed['DAYS_ENDDATE_FACT'] >= -16000]

In [30]:
bureau_closed['LATENCY'] =  bureau_closed['DAYS_CREDIT_ENDDATE'] - bureau_closed['DAYS_ENDDATE_FACT']
bureau_closed

/tmp/ipykernel_1745290/873638872.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_closed['LATENCY'] =  bureau_closed['DAYS_CREDIT_ENDDATE'] - bureau_closed['DAYS_ENDDATE_FACT']

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,...,DEBT_PERCENTAGE,DEBT_CREDIT_DIFF,CREDIT_TO_ANNUITY_RATIO,BUREAU_CREDIT_DEBT_RATIO,UTILIZATION_RATIO,UNPAID_CREDIT,AMT_CREDIT_MEAN,AMT_CREDIT_DEBT_MEAN,DURATION,LATENCY
0,5714462,Closed,currency 1,-497,0,-153.0,-153.0,0.0,0,91323.00,...,NaN,91323.00,NaN,0.0,NaN,1,91323.00,0.0,344.0,0.0
7,5714458,Closed,currency 1,-1872,0,-776.0,-1203.0,0.0,0,494550.00,...,NaN,494550.00,NaN,0.0,NaN,1,494550.00,0.0,1096.0,427.0
8,5714459,Closed,currency 1,-1734,0,-638.0,-1336.0,0.0,0,1084032.00,...,NaN,1084032.00,NaN,0.0,NaN,1,1084032.00,0.0,1096.0,698.0
9,5714460,Closed,currency 1,-1333,0,-1089.0,-987.0,0.0,0,102150.00,...,NaN,102150.00,NaN,0.0,NaN,1,102150.00,0.0,244.0,-102.0
10,5714461,Closed,currency 1,-1011,0,-830.0,-770.0,0.0,0,500463.00,...,NaN,500463.00,NaN,0.0,NaN,1,500463.00,0.0,181.0,-60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465319,5052615,Closed,currency 1,-697,0,-577.0,-577.0,0.0,0,27169.92,...,NaN,27169.92,NaN,0.0,NaN,1,27169.92,0.0,120.0,0.0
1465320,5052629,Closed,currency 1,-532,0,45.0,-227.0,0.0,0,450000.00,...,NaN,450000.00,NaN,0.0,NaN,1,450000.00,0.0,577.0,272.0
1465321,5054382,Closed,currency 1,-381,0,-199.0,-199.0,0.0,0,19800.00,...,NaN,19800.00,NaN,0.0,NaN,1,19800.00,0.0,182.0,0.0
1465323,5053303,Closed,currency 1,-375,0,-41.0,-19.0,0.0,0,175054.50,...,NaN,175054.50,9.0,0.0,NaN,1,175054.50,0.0,334.0,-22.0
1465324,5053356,Closed,currency 1,-2724,0,-2511.0,-2511.0,0.0,0,101250.00,...,NaN,101250.00,NaN,0.0,NaN,1,101250.00,0.0,213.0,0.0

In [31]:
(bureau_closed['LATENCY'] > 3200).sum()

43135

In [32]:
(bureau_closed['LATENCY'] < 0).sum()

205204

### Feature for close Bureau

- Count close bureau
- Sum overdue
- Count late
- Count early
- AVG duration
- AVG early
- AVG late
- 30 Day
- 90 Day
- 180 Day
- 365 Day
- 1000 Day
- Sum annuity

In [33]:
gb_bureau_close_count = bureau_active_close_feat(bureau_closed, 'CLOSE')
gb_bureau_close_count

/tmp/ipykernel_1745290/2824271316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -30, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_60_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -60, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_90_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -90, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -180, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_365_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -365, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LAST_1000_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] >= -1000, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["NEXT_30_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 30, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["NEXT_180_DAYS"] = np.where(bureau_active['DAYS_CREDIT'] <= 60, 1, 0)
/tmp/ipykernel_1745290/2824271316.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_active["LIFE_TIME_CREDIT"] = np.where(bureau_active['DAYS_CREDIT_ENDDATE'] >= 16000, 1, 0)

,SK_ID_CURR,CLOSE,CLOSE_LAST_90_DAYS,CLOSE_LAST_180_DAYS,CLOSE_LAST_365_DAYS,CLOSE_LAST_1000_DAYS,CLOSE_LIFE_TIME_CREDIT,CLOSE_CREDIT_TYPE,CLOSE_DAYS_CREDIT,CLOSE_AMT_CREDIT_SUM,...,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_DEBT_MEAN,CLOSE_AMT_CREDIT_SUM_LIMIT,CLOSE_AMT_ANNUITY,CLOSE_SUM_CREDIT_180_DAYS,CLOSE_SUM_CREDIT_LIFE_TIME,CLOSE_MEAN_DURATION_NOT_LIFE_TIME,CLOSE_LATENCY_180_DAYS,CLOSE_LATENCY_365_DAYS,CLOSE_MEAN_LATENCY
0,2,4,0,0,1,2,0,1,-247,153068.58,...,0.0,0.0,0.0,0.000,NaN,NaN,205.250000,NaN,0.0,21.000000
1,3,4,0,0,0,2,0,1,-675,271687.50,...,0.0,0.0,0.0,0.000,NaN,NaN,349.750000,NaN,NaN,32.500000
2,4,3,0,0,0,2,0,1,-942,1350000.00,...,0.0,0.0,0.0,0.000,NaN,NaN,1156.000000,NaN,NaN,924.000000
3,5,6,0,0,1,4,0,1,-265,24980728.50,...,0.0,0.0,0.0,429705.000,NaN,NaN,1530.500000,NaN,0.0,1031.333333
4,6,2,0,0,0,1,0,1,-917,1104210.00,...,0.0,0.0,0.0,0.000,NaN,NaN,995.500000,NaN,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230143,307501,4,0,0,1,2,1,2,-263,675132.30,...,0.0,0.0,0.0,24750.000,NaN,450000.0,232.666667,NaN,0.0,9.666667
230144,307504,3,0,0,0,1,0,1,-837,191153.25,...,0.0,0.0,0.0,0.000,NaN,NaN,302.000000,NaN,NaN,-1.333333
230145,307506,4,0,0,0,0,0,1,-1222,259263.00,...,0.0,0.0,0.0,0.000,NaN,NaN,275.000000,NaN,NaN,-20.250000
230146,307508,3,0,0,0,1,0,2,-652,5117872.50,...,0.0,0.0,0.0,8042.085,NaN,NaN,2090.000000,NaN,NaN,1064.666667
230147,307509,1,0,0,0,0,0,1,-2864,180000.00,...,0.0,0.0,0.0,0.000,NaN,NaN,549.000000,NaN,NaN,6.000000

In [34]:
bureau_closed.dropna(subset=['DAYS_ENDDATE_FACT'], inplace=True)

/tmp/ipykernel_1745290/1030630136.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_closed.dropna(subset=['DAYS_ENDDATE_FACT'], inplace=True)

## Sold and bad-debt

In [35]:
bureau_sold = bureau[bureau['CREDIT_ACTIVE'] == 'Sold']
bureau_sold

,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,...,ENDDATE_DIF,DEBT_PERCENTAGE,DEBT_CREDIT_DIFF,CREDIT_TO_ANNUITY_RATIO,BUREAU_CREDIT_DEBT_RATIO,UTILIZATION_RATIO,UNPAID_CREDIT,AMT_CREDIT_MEAN,AMT_CREDIT_DEBT_MEAN,DURATION
630,5715165,Sold,currency 1,-1319,0,-1134.0,365243.0,133308.81,0,202500.00,...,-366377.0,NaN,202500.00,NaN,0.0,NaN,1,202500.00,0.0,185.0
868,5715420,Sold,currency 1,-1337,0,-239.0,365243.0,0.00,0,477000.00,...,-365482.0,NaN,477000.00,NaN,0.0,NaN,1,477000.00,0.0,1098.0
1255,5715804,Sold,currency 1,-151,0,764.0,365243.0,0.00,0,435973.50,...,-364479.0,NaN,435973.50,NaN,0.0,NaN,1,435973.50,0.0,915.0
1568,5716119,Sold,currency 1,-2241,0,-1692.0,365243.0,0.00,0,142402.50,...,-366935.0,NaN,142402.50,NaN,0.0,NaN,1,142402.50,0.0,549.0
1779,5716347,Sold,currency 1,-2047,0,-1499.0,365243.0,0.00,0,153405.00,...,-366742.0,NaN,153405.00,NaN,0.0,NaN,1,153405.00,0.0,548.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463773,6839900,Sold,currency 1,-245,0,851.0,365243.0,0.00,0,90000.00,...,-364392.0,NaN,90000.00,9.0,0.0,NaN,1,90000.00,0.0,1096.0
1463813,6839973,Sold,currency 1,-2586,0,-1855.0,365243.0,82404.00,0,315000.00,...,-367098.0,NaN,315000.00,NaN,0.0,NaN,1,315000.00,0.0,731.0
1463868,6840152,Sold,currency 1,-2044,0,-1497.0,365243.0,0.00,0,148455.00,...,-366740.0,NaN,148455.00,9.0,0.0,NaN,1,148455.00,0.0,547.0
1464720,6842758,Sold,currency 1,-2232,0,-1501.0,365243.0,0.00,0,156973.50,...,-366744.0,NaN,156973.50,NaN,0.0,NaN,1,156973.50,0.0,731.0
1464808,6842885,Sold,currency 1,-709,0,1117.0,365243.0,0.00,0,461729.07,...,-364126.0,NaN,461729.07,NaN,0.0,NaN,1,461729.07,0.0,1826.0

### Feature Sold
- Total sold
- Sold finished
- Sold last 90
- Sold last 365
- Sold credit sum

### Feature Bad-Debt
- Total Bad debt
- Bad debt last 365
- Bad debt finished
- Sum credit debt
- Sum bad debt overdue
- Avg duration

In [36]:
bureau_sold = bureau[bureau['CREDIT_ACTIVE'] == 'Sold']

In [37]:
bureau_bad_debt = bureau[bureau['CREDIT_ACTIVE'] == 'Bad debt']

In [38]:
bureau_sold['SOLD_LAST_1000_DAYS'] = np.where(bureau_sold['DAYS_CREDIT'].values >= -1000, 1, 0)

bureau_sold['SOLD_FINISHED'] = np.where(bureau_sold['DAYS_ENDDATE_FACT'].isnull(), 0, 1)
bureau_sold['SOLD_DURATION'] = (bureau_sold['DAYS_ENDDATE_FACT'] - bureau_sold['DAYS_CREDIT']) * bureau_sold['SOLD_FINISHED']

/tmp/ipykernel_1745290/2334373062.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_sold['SOLD_LAST_1000_DAYS'] = np.where(bureau_sold['DAYS_CREDIT'].values >= -1000, 1, 0)
/tmp/ipykernel_1745290/2334373062.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_sold['SOLD_FINISHED'] = np.where(bureau_sold['DAYS_ENDDATE_FACT'].isnull(), 0, 1)
/tmp/ipykernel_1745290/2334373062.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_sold['SOLD_DURATION'] = (bureau_sold['DAYS_ENDDATE_FACT'] - bureau_sold['DAYS_CREDIT']) * bureau_sold['SOLD_FINISHED']

In [ ]:
gb_bureau_sold = bureau_sold.groupby('SK_ID_CURR').agg({ 'SOLD_LAST_1000_DAYS': 'sum', 'SOLD_FINISHED': 'sum', 'SOLD_DURATION':'sum'}).reset_index()
gb_bureau_sold['SOLD_DURATION'] = gb_bureau_sold['SOLD_DURATION']/(gb_bureau_sold['SOLD_FINISHED'] + 1e-5)

mask = (gb_bureau_sold['SOLD_FINISHED'] == 0)
gb_bureau_sold['SOLD_DURATION'] *= (gb_bureau_sold['SOLD_FINISHED'] != 0)
gb_bureau_sold['SOLD_DURATION'].loc[mask] = np.nan

/tmp/ipykernel_1745290/2914967014.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gb_bureau_sold['SOLD_DURATION'].loc[mask] = np.nan
/tmp/ipykernel_1745290/2914967014.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gb_bureau_sold['SOLD_DURATION'].loc[mask] = np.nan

In [40]:
bureau_bad_debt['BAD_DEBT_LAST_5_YEAR'] = np.where(bureau_bad_debt['DAYS_CREDIT'].values >= - 356*5, 1, 0)
bureau_bad_debt['BAD_DEBT_FINISHED'] = np.where(bureau_bad_debt['DAYS_ENDDATE_FACT'].isnull(), 0, 1)
gb_bureau_bad_debt = bureau_bad_debt.groupby('SK_ID_CURR').agg({ 'BAD_DEBT_LAST_5_YEAR': 'sum', 'BAD_DEBT_FINISHED': 'sum'}).reset_index()

/tmp/ipykernel_1745290/3613541578.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_bad_debt['BAD_DEBT_LAST_5_YEAR'] = np.where(bureau_bad_debt['DAYS_CREDIT'].values >= - 356*5, 1, 0)
/tmp/ipykernel_1745290/3613541578.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bureau_bad_debt['BAD_DEBT_FINISHED'] = np.where(bureau_bad_debt['DAYS_ENDDATE_FACT'].isnull(), 0, 1)

## Merge all

In [41]:
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_active_count, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_close_count, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_sold, on='SK_ID_CURR', how='left')
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_bad_debt, on='SK_ID_CURR', how='left')

gb_bureau_general.head()

,SK_ID_CURR,GENERAL_SK_ID_BUREAU_count,GENERAL_AMT_CREDIT_SUM_sum,GENERAL_AMT_CREDIT_SUM_mean,GENERAL_AMT_CREDIT_SUM_std,GENERAL_AMT_CREDIT_SUM_DEBT_sum,GENERAL_AMT_CREDIT_SUM_DEBT_mean,GENERAL_AMT_CREDIT_SUM_DEBT_std,GENERAL_AMT_CREDIT_SUM_OVERDUE_sum,GENERAL_AMT_ANNUITY_sum,...,CLOSE_SUM_CREDIT_LIFE_TIME,CLOSE_MEAN_DURATION_NOT_LIFE_TIME,CLOSE_LATENCY_180_DAYS,CLOSE_LATENCY_365_DAYS,CLOSE_MEAN_LATENCY,SOLD_LAST_1000_DAYS,SOLD_FINISHED,SOLD_DURATION,BAD_DEBT_LAST_5_YEAR,BAD_DEBT_FINISHED
0,0,1,85513.50,85513.500000,NaN,77566.5,77566.500000,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,28350.00,28350.000000,NaN,0.0,0.000000,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6,254341.08,42390.180000,27030.097199,96417.0,16069.500000,25705.163734,0.0,0.0,...,NaN,205.25,NaN,0.0,21.0,NaN,NaN,NaN,NaN,NaN
3,3,7,483952.50,69136.071429,41184.078332,198769.5,28395.642857,58477.076226,0.0,0.0,...,NaN,349.75,NaN,NaN,32.5,NaN,NaN,NaN,NaN,NaN
4,4,6,2822544.00,470424.000000,317857.683022,1254505.5,209084.250000,264456.157378,0.0,0.0,...,NaN,1156.00,NaN,NaN,924.0,NaN,NaN,NaN,NaN,NaN

## Merge with Bureau Balance

In [42]:
bureau_balance = pd.read_csv('../../data/dseb63_bureau_balance_aggregated.csv')

In [43]:
bureau_balance

,SK_ID_BUREAU,C Last 24 Month,X Last 24 Month,0 Last 24 Month,1 Last 24 Month,5 Last 24 Month,2-4 Last 24 Month,MAX_MONTHS_BALANCE,TOTAL_MONTHS,Ratio C,Ratio X,Ratio 0,Ratio Other
0,5001718,3,7,13,2,0,0,0,39,3,10,24,2
1,5001844,16,3,5,1,0,0,0,48,16,12,19,1
2,5001922,19,3,2,1,0,0,0,36,19,9,7,1
3,5001981,25,0,0,0,0,0,0,67,60,1,3,3
4,5001988,5,6,14,0,0,0,0,53,5,15,32,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20699,6842759,25,0,0,0,0,0,0,74,43,9,8,14
20700,6842765,21,3,1,0,0,0,0,49,21,9,18,1
20701,6842791,25,0,0,0,0,0,0,53,40,8,3,2
20702,6842874,25,0,0,0,0,0,0,90,80,1,8,1
20703,6842880,25,0,0,0,0,0,0,58,36,13,7,2

In [44]:
bureau_balance = pd.merge(bureau_balance, bureau[['SK_ID_CURR', 'SK_ID_BUREAU']], on='SK_ID_BUREAU', how='left')

In [46]:
bureau_balance.dropna(subset=['SK_ID_CURR'], inplace=True)

In [47]:
bureau_balance['SK_ID_CURR'].nunique()

8196

In [48]:
gb_bureau_balance = bureau_balance.groupby('SK_ID_CURR').agg({'0 Last 24 Month':'sum', 'TOTAL_MONTHS':'sum', 'Ratio C':'sum' , 'Ratio X':'sum', 'Ratio 0':'sum', 'Ratio Other': 'sum'}).reset_index()
gb_bureau_balance['Ratio C'] = gb_bureau_balance['Ratio C']/gb_bureau_balance['TOTAL_MONTHS'] * (gb_bureau_balance['TOTAL_MONTHS'] != 0)
gb_bureau_balance['Ratio X'] = gb_bureau_balance['Ratio X']/gb_bureau_balance['TOTAL_MONTHS'] * (gb_bureau_balance['TOTAL_MONTHS'] != 0)
gb_bureau_balance['Ratio 0'] = gb_bureau_balance['Ratio 0']/gb_bureau_balance['TOTAL_MONTHS'] * (gb_bureau_balance['TOTAL_MONTHS'] != 0)
gb_bureau_balance['Ratio Other'] = gb_bureau_balance['Ratio Other']/gb_bureau_balance['TOTAL_MONTHS'] * (gb_bureau_balance['TOTAL_MONTHS'] != 0)

gb_bureau_balance.drop(columns=['TOTAL_MONTHS'], inplace=True)

In [49]:
gb_bureau_general = pd.merge(gb_bureau_general, gb_bureau_balance, on='SK_ID_CURR', how='left')

In [50]:
gb_bureau_general

,SK_ID_CURR,GENERAL_SK_ID_BUREAU_count,GENERAL_AMT_CREDIT_SUM_sum,GENERAL_AMT_CREDIT_SUM_mean,GENERAL_AMT_CREDIT_SUM_std,GENERAL_AMT_CREDIT_SUM_DEBT_sum,GENERAL_AMT_CREDIT_SUM_DEBT_mean,GENERAL_AMT_CREDIT_SUM_DEBT_std,GENERAL_AMT_CREDIT_SUM_OVERDUE_sum,GENERAL_AMT_ANNUITY_sum,...,SOLD_LAST_1000_DAYS,SOLD_FINISHED,SOLD_DURATION,BAD_DEBT_LAST_5_YEAR,BAD_DEBT_FINISHED,0 Last 24 Month,Ratio C,Ratio X,Ratio 0,Ratio Other
0,0,1,85513.50,8.551350e+04,NaN,77566.5,77566.500000,NaN,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,28350.00,2.835000e+04,NaN,0.0,0.000000,NaN,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6,254341.08,4.239018e+04,2.703010e+04,96417.0,16069.500000,25705.163734,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,7,483952.50,6.913607e+04,4.118408e+04,198769.5,28395.642857,58477.076226,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,6,2822544.00,4.704240e+05,3.178577e+05,1254505.5,209084.250000,264456.157378,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263486,307504,4,866153.25,2.165383e+05,3.057300e+05,119767.5,29941.875000,59883.750000,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263487,307505,2,3618000.00,1.809000e+06,1.794637e+06,0.0,0.000000,0.000000,0.0,180927.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263488,307506,4,259263.00,6.481575e+04,4.983890e+04,0.0,0.000000,0.000000,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263489,307508,7,5506306.83,7.866153e+05,1.643068e+06,251748.0,35964.000000,41886.032956,0.0,25476.255,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263490,307509,2,315000.00,1.575000e+05,3.181981e+04,27900.0,13950.000000,19728.279195,0.0,0.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Add some features

In [51]:
gb_bureau_general['DEBT_CREDIT_RATIO'] = gb_bureau_general['GENERAL_AMT_CREDIT_SUM_DEBT_sum'] / (gb_bureau_general['GENERAL_AMT_CREDIT_SUM_sum'] + 1e-5) * (gb_bureau_general['GENERAL_AMT_CREDIT_SUM_sum'] != 0)
mask = (gb_bureau_general['GENERAL_AMT_CREDIT_SUM_sum'] == 0)
gb_bureau_general['DEBT_CREDIT_RATIO'].loc[mask] = np.nan

/tmp/ipykernel_1745290/3731598542.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gb_bureau_general['DEBT_CREDIT_RATIO'].loc[mask] = np.nan
/tmp/ipykernel_1745290/3731598542.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gb_bureau_general['DEBT_CREDIT_RATIO'].loc[mask] = np.nan

In [52]:
gb_bureau_general.to_parquet('../../data/dseb63_bureau_general_v3_2.parquet', index=False)